Repository milvus-io/knowhere, pull requests merged in 2022-11, with the labels that each got.

#520 Release free mem in diskann aligned_free function
  thirdparty/DiskANN/include/utils.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#517 Make the Query thread pool global
  .github/workflows/ut.yaml
  knowhere/CMakeLists.txt
  knowhere/common/ThreadPoolHolder.cpp
  knowhere/common/ThreadPoolHolder.h
  knowhere/index/vector_index/IndexHNSW.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#522 Add thread pool to diskann search
  knowhere/CMakeLists.txt
  knowhere/common/ThreadPool.cpp
  knowhere/common/ThreadPool.h
  knowhere/common/ThreadPoolHolder.cpp
  knowhere/common/ThreadPoolHolder.h
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#521 Support Feder for DiskANN
  knowhere/feder/DiskANN.h
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/test_diskann.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#527 Remove stats in hnsw
  knowhere/index/vector_index/IndexHNSW.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#529 Fix HNSW/DiskANN feder memory leak
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#528 Refactor knowhere range search to accept 2-side boundaries
  knowhere/archive/BruteForce.cpp
  knowhere/feder/DiskANN.h
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexBinaryIVF.h
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVF.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_index/helpers/RangeUtil.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_multi.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_multi_qps.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_qps.cpp
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range_multi.cpp
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range_multi_qps.cpp
  unittest/range_utils.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_bruteforce.cpp
  unittest/test_diskann.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
  unittest/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/XXL, dco-passed

#534 Update release for current branch
  .github/workflows/release.yaml
Labels: kind/improvement, lgtm, approved, dco-passed, size/XS

#539 Port benchmark from knowhere-v1.3
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/benchmark_base.h
  benchmark/hdf5/benchmark_hdf5.h
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/benchmark_knowhere_float.cpp
  benchmark/prepare.sh
  benchmark/utils.h
  include/knowhere/comp/index_param.h
  include/knowhere/dataset.h
  thirdparty/gtest/CMakeLists.txt
Labels: size/XXL

#535 [skip e2e]Submit knowhere2.0 ci jenkins script
  ci/E2E2.groovy
Labels: kind/improvement, lgtm, size/M

#541 Add thread pool for DiskANN and HNSW search
  include/knowhere/ThreadPool.h
  include/knowhere/ctpl/ctpl-std.h
  include/knowhere/ctpl/ctpl.h
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
Labels: lgtm, size/XL

#542 Remove stats in HNSW
  src/index/hnsw/hnsw.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: lgtm, size/M

#543 Move thread_pool.h to src/common
  src/common/ctpl/ctpl-std.h
  src/common/ctpl/ctpl.h
  src/common/thread_pool.h
  src/index/diskann/diskann.cc
  src/index/hnsw/hnsw.cc
Labels: size/XS

#537 Use elkan's algo to accelerate KMeans
  thirdparty/DiskANN/include/math_utils.h
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#544 Support range search for HNSW and faiss index types
  include/knowhere/comp/brute_force.h
  include/knowhere/comp/metric_type.h
  include/knowhere/config.h
  include/knowhere/dataset.h
  include/knowhere/knowhere.h
  src/common/comp/brute_force.cc
  src/common/metric.h
  src/common/range_util.cc
  src/common/range_util.h
  src/index/annoy/annoy.cc
  src/index/example/simple_config.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: lgtm, size/XL

#545 Support range search for DiskANN
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, size/M

#550 Remove dim from BaseConfig
  include/knowhere/config.h
  src/index/example/simple_config.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_config.cc
Labels: lgtm, size/M

#546 Add prefetch in hnsw
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#551 Support feder for IVFFlat, HNSW and DiskANN
  include/knowhere/config.h
  include/knowhere/dataset.h
  include/knowhere/feder/DiskANN.h
  include/knowhere/feder/HNSW.h
  include/knowhere/feder/IVFFlat.h
  include/knowhere/knowhere.h
  src/index/annoy/annoy.cc
  src/index/diskann/diskann.cc
  src/index/example/simple_config.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: lgtm, size/XL

#552 Optimize hnsw search
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#554 Add range_util unittest
  src/common/range_util.cc
  tests/ut/test_range_util.cc
  tests/ut/utils.h
Labels: lgtm, size/L

#553 Optimize hnsw search algo
  knowhere/index/vector_index/IndexHNSW.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  thirdparty/hnswlib/hnswlib/neighbor.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#556 Fix HNSW get dim
  include/knowhere/knowhere.h
  src/index/hnsw/hnsw.cc
Labels: lgtm, size/M

#560 Move all index related consts into index_param.h
  benchmark/hdf5/benchmark_knowhere_float.cpp
  include/knowhere/comp/index_param.h
  include/knowhere/comp/index_type.h
  include/knowhere/comp/metric_type.h
  include/knowhere/dataset.h
  src/common/metric.h
  src/index/diskann/diskann.cc
  src/index/hnsw/hnsw.cc
Labels: size/L

#561 [skip e2e]Delete Unit Test on windows
  .github/mergify.yml
  .github/workflows/ut.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#558 Add some logs for diskann
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/cached_io.h
  thirdparty/DiskANN/include/diskann/logger.h
  thirdparty/DiskANN/include/diskann/pq_table.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: size/L

#563 add ci ut check
  .devcontainer.json
  .github/mergify.yml
  .github/workflows/pre-commit.yml
  .github/workflows/publish-builder.yaml
  .github/workflows/release.yaml
  .github/workflows/ut.yaml
  .pre-commit-config.yaml
  ci/Jenkinsfile
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  scripts/install_deps.sh
Labels: size/L

#564 add rangesearch api for python wrapper
  python/knowhere/knowhere.i
Labels: size/XS

#562 Add some checks and ut for diskann
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
  tests/ut/utils.h
Labels: lgtm, size/L

#566 Support diskann index in python api and add a pytest case
  README.md
  ci/E2E2.groovy
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  tests/python/test_diskann.py
Labels: size/L

#568 Replace diskann compute function with faiss's compute function
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#567 Fix aio io_getevents
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#570 Add Thread Pool for all indexes in Knowhere
  knowhere/index/VecIndexFactory.cpp
  knowhere/index/VecIndexThreadPoolWrapper.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexAnnoy.h
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  knowhere/index/vector_index/gpu/IndexGPUIDMAP.h
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#569 Add API GenResultDataSet()
  CMakeLists.txt
  include/knowhere/dataset.h
  src/index/annoy/annoy.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/flat_gpu/flat_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_gpu/ivf_gpu.cc
Labels: lgtm, size/L

#573 Rename some APIs
  include/knowhere/knowhere.h
  python/knowhere/knowhere.i
  src/index/annoy/annoy.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/flat_gpu/flat_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_gpu/ivf_gpu.cc
  tests/ut/test_search.cc
Labels: lgtm, size/L

#571 Use nothrow while creating quantizer
  src/index/ivf/ivf.cc
Labels: lgtm, size/XS
