Repository milvus-io/knowhere, pull requests merged in 2022-07, with the labels that each got.

#229 Revert #226
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  thirdparty/faiss/faiss/Index.cpp
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexBinary.cpp
  thirdparty/faiss/faiss/IndexBinary.h
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryFlat.h
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexFlatCodes.cpp
  thirdparty/faiss/faiss/IndexFlatCodes.h
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#233 [skip e2e]Add publish builder for knowhere
  .env
  .github/workflows/publish-builder.yaml
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  docker-compose.yml
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#232 Add range search python3 api and opted swig wrapper.
  knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVFPQ.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVFSQ.cpp
  knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  python/setup.py
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#236 [skip e2e]Add test for knowhere
  .env
  README.md
  ci/Jenkinsfile
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  ci/pod/test.yaml
Labels: kind/improvement, size/L, dco-passed

#237 Format the swig script code and add simd support for python api
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  python/setup.py
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#239 Optimize range search unittest
  unittest/range_utils.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#240 Add API BruteForceSearch()
  knowhere/CMakeLists.txt
  knowhere/archive/BruteForce.cpp
  knowhere/archive/BruteForce.h
  unittest/CMakeLists.txt
  unittest/test_bruteforce.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#245 Update mergify rule
  .github/mergify.yml
Labels: kind/improvement, dco-passed, size/XS, do-not-merge/missing-related-issue

#241 Add commit id & date & branch
  ci/Jenkinsfile
Labels: kind/improvement, dco-passed, size/XS

#246 Change distance_compute_blas_threshold default value from 20 to 65535
  thirdparty/faiss/faiss/utils/distances.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#247 Always change metric type string to uppercase
  knowhere/archive/BruteForce.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/test_bruteforce.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#243 Add API BruteForceRangeSearch()
  knowhere/archive/BruteForce.cpp
  knowhere/archive/BruteForce.h
  unittest/test_bruteforce.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#248 Update mount test data address
  ci/pod/test.yaml
Labels: dco-passed, size/S, do-not-merge/hold, do-not-merge/missing-related-issue

#254 Add interface for Disk Index's file operator
  knowhere/common/FileManager.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#257 Optimize benchmark to do distance checking
  unittest/benchmark/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/benchmark_knowhere_float_range.cpp
  unittest/benchmark/benchmark_sift.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#258 Add archive logs and abort last build
  ci/Jenkinsfile
  ci/pod/cpu-e2e.yaml
Labels: kind/improvement, dco-passed, size/S

#259 Fix gpu ivf flat core dump bug
  thirdparty/faiss/faiss/IndexIVF.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#263 Add node selector for knowhere
  ci/Jenkinsfile
  ci/pod/cpu-e2e.yaml
Labels: kind/improvement, dco-passed, size/XS

#261 Python wheel add version label
  ci/Jenkinsfile
  python/setup.py
  unittest/test_idmap.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#264 Use new namespace for knowhere
  ci/Jenkinsfile
  ci/pod/cpu-e2e.yaml
Labels: kind/improvement, dco-passed, size/XS

#267 Use release instead of debug
  ci/Jenkinsfile
Labels: kind/improvement, dco-passed, size/XS

#269 Update Dockfile for ubuntu20.04
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, approved, dco-passed, size/S

#274 Update cpu-e2e to 8c32g
  ci/pod/cpu-e2e.yaml
Labels: kind/improvement, dco-passed, size/XS

#277 [skip e2e]Add skip e2e rules for mergify
  .github/mergify.yml
Labels: kind/improvement, dco-passed, size/S

#279 Change distance_compute_blas_threshold default value to 16384
  thirdparty/faiss/faiss/utils/distances.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#280 Replace docker image for build & e2e
  ci/pod/cpu-build.yaml
  ci/pod/cpu-e2e.yaml
Labels: kind/improvement, dco-passed, size/XS

#281 [skip e2e]Add action to build docker images
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-docker.yaml
  ci/docker/ubuntu/Dockerfile
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/debug.sh
  ci/docker/ubuntu/scripts/deps/e2e.sh
Labels: kind/improvement, ci-passed, size/L, dco-passed

#285 Move archive logs to post
  ci/Jenkinsfile
Labels: kind/improvement, dco-passed, size/S

#266 Add GPU e2e
  ci/GpuE2E.groovy
  ci/pod/gpu-build.yaml
  ci/pod/gpu-e2e.yaml
Labels: kind/improvement, size/L, dco-passed

#282 Python api add bin_ivf
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#265 DiskANN CMake Support
  .github/workflows/ut.yaml
  build.sh
  cmake/DefineOptionsKw.cmake
  cmake/ThirdPartyPackagesKw.cmake
  knowhere/CMakeLists.txt
  scripts/install_deps.sh
  thirdparty/CMakeLists.txt
  thirdparty/DiskANN/src/CMakeLists.txt
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#268 Update benchmark params and ref logs
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/benchmark_faiss.cpp
  unittest/benchmark/benchmark_knowhere_binary.cpp
  unittest/benchmark/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/benchmark_knowhere_float_range.cpp
  unittest/benchmark/benchmark_knowhere_perf.cpp
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_hnsw.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_idmap.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_ivf_flat.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_ivf_sq8.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_tanimoto.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_tanimoto.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary_range/test_knowhere_binary_range_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary_range/test_knowhere_binary_range_ivf_flat.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_hnsw.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_flat.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_sq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/XXL, dco-passed

#290 Remove unnecessary dependencies: lapack v3.8.0
  thirdparty/versions.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#293 [skip e2e] Update hardware environment in benchmark README.txt
  unittest/benchmark/README.md
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#299 Remove IVF_SQ8H from VecIndexFactory
  knowhere/index/VecIndexFactory.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#297 DiskANN cmake code formatting
  .github/workflows/ut.yaml
  build.sh
  cmake/DefineOptionsKw.cmake
  cmake/ThirdPartyPackagesKw.cmake
  knowhere/CMakeLists.txt
  scripts/install_deps.sh
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#295 Python api add gpu flat
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#307 Add Bitsetview support in DiskANN
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/tests/range_search_disk_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#308 Add id validation check for GetVectorById()
  knowhere/common/Exception.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVFPQ.h
  knowhere/index/vector_index/IndexIVFSQ.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  thirdparty/faiss/faiss/Index.cpp
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexBinary.cpp
  thirdparty/faiss/faiss/IndexBinary.h
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryFlat.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVF.h
  thirdparty/faiss/faiss/IndexFlat.cpp
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf_hnsw.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#309 Support Filemanager in DiskANN code
  knowhere/common/FileManager.h
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  thirdparty/DiskANN/include/pq_table.h
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/tests/utils/gen_random_slice.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#310 Update log to print out radius
  knowhere/archive/BruteForce.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/benchmark/benchmark_knowhere_binary.cpp
  unittest/benchmark/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/benchmark_knowhere_float_range.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#313 [skip e2e] Add benchmark ref logs for glove test
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_hnsw.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_rhnsw_flat.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_rhnsw_pq.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_rhnsw_sq.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_idmap.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_ivf_pq.log
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
  unittest/benchmark/ref_log/sift/benchmark_faiss/test_faiss_hnsw.log
  unittest/benchmark/ref_log/sift/benchmark_faiss/test_faiss_idmap.log
  unittest/benchmark/ref_log/sift/benchmark_faiss/test_faiss_ivf_flat.log
  unittest/benchmark/ref_log/sift/benchmark_faiss/test_faiss_ivf_pq.log
  unittest/benchmark/ref_log/sift/benchmark_faiss/test_faiss_ivf_sq8.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_idmap_hamming.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_idmap_jaccard.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_idmap_tanimoto.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_hamming.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_jaccard.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_tanimoto.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary_range/test_knowhere_binary_range_idmap.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_binary_range/test_knowhere_binary_range_ivf_flat.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_hnsw.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_rhnsw_flat.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_rhnsw_pq.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float/test_knowhere_rhnsw_sq.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_idmap.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_pq.log
  unittest/benchmark/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#316 Set correct metric type for RHNSW_PQ
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWPQ.cpp
  knowhere/index/vector_index/IndexRHNSWPQ.h
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  thirdparty/faiss/faiss/IndexRHNSW.cpp
  thirdparty/faiss/faiss/IndexRHNSW.h
  unittest/benchmark/ref_log/glove/benchmark_knowhere_float/test_knowhere_rhnsw_pq.log
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#315 Add diskann build params check
  knowhere/index/vector_index/IndexDiskANN.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#314 Move build binary can be scheduled to non-gpu nodes
  ci/pod/cpu-build.yaml
  ci/pod/gpu-build.yaml
Labels: kind/improvement, dco-passed, size/XS

#324 Refactor node selector
  ci/GpuE2E.groovy
  ci/Jenkinsfile
  ci/pod/gpu-build.yaml
Labels: kind/improvement, dco-passed, size/S

#322 Add test_vecindex.cpp to check both L2 and IP metric types
  unittest/CMakeLists.txt
  unittest/Helper.h
  unittest/test_vecindex.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#325 Remove knowhere version
  CMakeLists.txt
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#323 Support metric type lower case when use python api
  python/knowhere/knowhere.i
Labels: ci-passed, dco-passed, size/XS

#326 Remove meta::SLICE_SIZE from common config and set it only in slice ut
  unittest/Helper.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_hnsw.cpp
  unittest/test_rhnsw.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#320 Link MKL to libknowhere
  cmake/ThirdPartyPackagesKw.cmake
  knowhere/CMakeLists.txt
  thirdparty/CMakeLists.txt
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/src/CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#327 Fix ut in gpu mode
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  unittest/CMakeLists.txt
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#330 [skip e2e]Add gpu check rule
  .github/mergify.yml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed

#331 [skip e2e]Add gpu check rule
  .github/mergify.yml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#333 Avoid using find_package(MKL) to fix error
  cmake/ThirdPartyPackagesKw.cmake
  thirdparty/DiskANN/src/CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#321 Reduce the memory usage of thread data's coord_scratch
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#317 Fix some problem in DiskANN support
  knowhere/CMakeLists.txt
  knowhere/common/FileManager.h
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M
