Repository milvus-io/knowhere, pull requests merged in 2022-04, with the labels that each got.

#104 Fix some build warnings
  cmake/ThirdPartyPackagesKw.cmake
  knowhere/CMakeLists.txt
  thirdparty/faiss/faiss/utils/distances.cpp
Labels: lgtm, approved, size/S

#105 Move lookup8bit from distances_simd_avx.cpp to distances_simd.cpp
  knowhere/utils/distances_simd.cpp
  knowhere/utils/distances_simd.h
  knowhere/utils/distances_simd_avx.cpp
  knowhere/utils/distances_simd_avx.h
  thirdparty/faiss/faiss/utils/BinaryDistance.cpp
  thirdparty/faiss/faiss/utils/hamming.cpp
Labels: lgtm, approved, size/M

#106 Change default fvec APIs to _ref for mac
  knowhere/utils/FaissHookFvec.cpp
  knowhere/utils/FaissHookFvec.h
Labels: lgtm, approved, size/S

#107 Change sq8 default fvec APIs to _ref for mac
  thirdparty/faiss/faiss/FaissHook.cpp
Labels: lgtm, approved, size/S

#108 Disable AVX2 binary distance calculation for mac
  thirdparty/faiss/faiss/utils/BinaryDistance.cpp
Labels: lgtm, approved, size/S

#109 Optimize knowhere CMakeLists.txt
  knowhere/CMakeLists.txt
  thirdparty/CMakeLists.txt
  thirdparty/faiss/CMakeLists.txt
  unittest/CMakeLists.txt
Labels: lgtm, approved, size/L

#110 Remove redundant cmake settings
  CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: lgtm, approved, size/M

#111 Remove redundant init log from unittest
  unittest/test_common.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: lgtm, approved, size/S

#112 Update test_common
  unittest/test_common.cpp
Labels: lgtm, approved, size/S

#114 Remove useless old IndexType
  knowhere/index/IndexType.cpp
  knowhere/index/IndexType.h
  knowhere/index/vector_index/ConfAdapterMgr.cpp
Labels: lgtm, approved, size/M

#113 Support build for MacOS
  CMakeLists.txt
  cmake/ThirdPartyPackagesKw.cmake
  knowhere/CMakeLists.txt
  knowhere/archive/KnowhereConfig.cpp
  knowhere/common/Log.cpp
  knowhere/index/vector_index/VecIndex.h
  knowhere/index/vector_index/VecIndexFactory.cpp
  knowhere/utils/CMakeLists.txt
  knowhere/utils/FaissHookFvec.h
  scripts/install_deps.sh
  thirdparty/CMakeLists.txt
  thirdparty/faiss/faiss/CMakeLists.txt
  unittest/CMakeLists.txt
  unittest/utils.h
Labels: lgtm, approved, size/XL

#115 Update create index factory
  knowhere/index/IndexType.h
  knowhere/index/vector_index/ConfAdapterMgr.cpp
  knowhere/index/vector_index/VecIndexFactory.cpp
Labels: lgtm, approved, size/L

#116 Fix Mac M1 build error
  knowhere/utils/FaissHookFvec.cpp
  thirdparty/faiss/faiss/CMakeLists.txt
  unittest/CMakeLists.txt
Labels: lgtm, approved, size/M

#118 Update benchmark
  unittest/CMakeLists.txt
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/README.md
  unittest/benchmark/benchmark_faiss_test.cpp
  unittest/benchmark/benchmark_knowhere_test.cpp
Labels: lgtm, approved, size/XL

#119 Update CMakeLists.txt
  CMakeLists.txt
  unittest/benchmark/benchmark_knowhere_test.cpp
Labels: lgtm, approved, size/S

#121 Change SetIndexFileSliceSize to static
  knowhere/archive/KnowhereConfig.h
Labels: lgtm, approved, size/XS

#122 Remove boost and tbb from install_deps.sh
  scripts/install_deps.sh
Labels: lgtm, approved, size/S

#123 Remove BruteForce related files
  build.sh
  knowhere/CMakeLists.txt
  knowhere/common/Heap.cpp
  knowhere/common/Heap.h
  knowhere/index/vector_index/impl/bruteforce/BruteForce.cpp
  knowhere/index/vector_index/impl/bruteforce/BruteForce.h
  knowhere/index/vector_index/impl/bruteforce/SimpleIndexFlat.cpp
  knowhere/index/vector_index/impl/bruteforce/SimpleIndexFlat.h
  unittest/CMakeLists.txt
  unittest/test_bruteforce.cpp
Labels: lgtm, approved, size/XXL

#124 Combine Config.h and Json.h into one file
  knowhere/common/Config.h
  knowhere/common/Json.h
Labels: lgtm, approved, size/M

#126 Remove structured index
  knowhere/index/structured_index/StructuredIndex.h
  knowhere/index/structured_index/StructuredIndexFlat-inl.h
  knowhere/index/structured_index/StructuredIndexFlat.h
  knowhere/index/structured_index/StructuredIndexSort-inl.h
  knowhere/index/structured_index/StructuredIndexSort.h
  knowhere/index/structured_index_simple/StructuredIndex.h
  knowhere/index/structured_index_simple/StructuredIndexFlat-inl.h
  knowhere/index/structured_index_simple/StructuredIndexFlat.h
  knowhere/index/structured_index_simple/StructuredIndexSort-inl.h
  knowhere/index/structured_index_simple/StructuredIndexSort.h
  unittest/CMakeLists.txt
  unittest/test_structured_index_flat.cpp
  unittest/test_structured_index_sort.cpp
Labels: lgtm, approved, size/XXL

#128 Remove unused benchmark code
  unittest/faiss_benchmark/CMakeLists.txt
  unittest/faiss_benchmark/README.md
  unittest/faiss_benchmark/faiss_benchmark_test.cpp
  unittest/faiss_benchmark/faiss_bitset_test.cpp
  unittest/metric_alg_benchmark/CMakeLists.txt
  unittest/metric_alg_benchmark/metric_benchmark_test.cpp
Labels: lgtm, approved, size/XXL

#125 Remove ConcurrentBitset
  knowhere/index/vector_index/Statistics.h
  knowhere/index/vector_index/impl/nsg/NSG.cpp
  knowhere/utils/BitsetView.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFSpectralHash.cpp
  thirdparty/faiss/faiss/gpu/GpuIndexFlat.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFFlat.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFPQ.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFSQHybrid.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFScalarQuantizer.cu
  thirdparty/faiss/faiss/impl/ResultHandler.h
  thirdparty/faiss/faiss/impl/ScalarQuantizer.h
  thirdparty/faiss/faiss/utils/BinaryDistance.cpp
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/extra_distances.cpp
  thirdparty/hnswlib/hnswalg.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_common.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_cpu_nm.cpp
  unittest/test_ivf_gpu_nm.cpp
  unittest/test_ngtonng.cpp
  unittest/test_ngtpanng.cpp
  unittest/test_nsg.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
  unittest/utils.h
Labels: lgtm, approved, size/XL, do-not-merge/hold

#129 Remove std::cout from knowhere and faiss
  knowhere/utils/FaissHookFvec.cpp
  thirdparty/faiss/faiss/FaissHook.cpp
  unittest/benchmark/benchmark_faiss_test.cpp
  unittest/benchmark/benchmark_knowhere_test.cpp
  unittest/utils.h
Labels: lgtm, approved, size/S

#130 Add mergify rule for ci-passed & dco check
  .github/mergify.yml
Labels: kind/improvement, lgtm, approved, size/M

#132 Update mergify rule
  .github/mergify.yml
Labels: kind/improvement, lgtm, approved, dco-passed, size/S

#68 Support under Windows/MSYS
  .github/workflows/ut.yaml
  CMakeLists.txt
  build.sh
  knowhere/common/Log.cpp
  knowhere/index/vector_index/ConfAdapterMgr.cpp
  knowhere/index/vector_index/ConfAdapterMgr.h
  knowhere/index/vector_index/helpers/SPTAGParameterMgr.cpp
  knowhere/index/vector_index/helpers/SPTAGParameterMgr.h
  knowhere/index/vector_index/impl/nsg/NSG.cpp
  knowhere/utils/distances_simd_sse.cpp
  scripts/install_deps.sh
  thirdparty/CMakeLists.txt
  thirdparty/NGT/CMakeLists.txt
  thirdparty/NGT/lib/CMakeLists.txt
  thirdparty/NGT/lib/NGT/CMakeLists.txt
  thirdparty/NGT/lib/NGT/Common.h
  thirdparty/NGT/lib/NGT/GetCoreNumber.cpp
  thirdparty/NGT/lib/NGT/Index.h
  thirdparty/NGT/lib/NGT/MmapManager.cpp
  thirdparty/NGT/lib/NGT/MmapManagerDefs.h
  thirdparty/NGT/lib/NGT/SharedMemoryAllocator.h
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/impl/platform_macros.h
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.cpp
  thirdparty/mman-win32/README.md
  thirdparty/mman-win32/sys/mman.h
  unittest/CMakeLists.txt
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_common.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ngtonng.cpp
  unittest/test_ngtpanng.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
  unittest/test_sptag.cpp
  unittest/test_wrapper.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#133 Update mergify rule for adding unit test on MSYS
  .github/mergify.yml
Labels: kind/improvement, lgtm, approved, dco-passed, size/XS

#134 Optimize test_idmap and test_binaryidmap
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexPQ.h
  thirdparty/faiss/faiss/utils/BinaryDistance.h
  thirdparty/faiss/faiss/utils/distances.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#135 Remove unused SPTAG.cpp
  unittest/SPTAG.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#127 Add python wrapper for index test case developing
  .gitignore
  README.md
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  python/numpy.i
  python/setup.py
  unittest/pycase/test_annoy.py
  unittest/pycase/test_hnsw.py
  unittest/pycase/test_ivf.py
  unittest/pycase/test_ivfsq.py
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#137 Optimize range_search for idmap
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/VecIndex.h
  knowhere/index/vector_index/helpers/DynamicResultSet.cpp
  knowhere/index/vector_index/helpers/DynamicResultSet.h
  thirdparty/faiss/faiss/IndexFlat.cpp
  thirdparty/faiss/faiss/utils/distances_range.cpp
  thirdparty/faiss/faiss/utils/distances_range.h
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#138 Remove useless Uids
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexRHNSW.cpp
  knowhere/index/vector_index/VecIndex.h
  knowhere/index/vector_index/helpers/Cloner.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#140 Enable cpplint & clang-format check for ubuntu
  .github/workflows/ut.yaml
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/helpers/DynamicResultSet.cpp
  knowhere/index/vector_index/helpers/DynamicResultSet.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#139 Refactor range search for idmap
  knowhere/common/Dataset.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/VecIndex.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexFlat.cpp
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/impl/ResultHandler.h
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
  thirdparty/faiss/faiss/utils/distances_range.cpp
  thirdparty/faiss/faiss/utils/distances_range.h
  unittest/test_idmap.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#141 Add SimdType::GENERIC
  knowhere/archive/KnowhereConfig.cpp
  knowhere/archive/KnowhereConfig.h
  unittest/benchmark/benchmark_faiss_test.cpp
  unittest/benchmark/benchmark_knowhere_test.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#142 Update idmap unittest to run both SIMD and BLAS
  knowhere/archive/KnowhereConfig.cpp
  knowhere/archive/KnowhereConfig.h
  unittest/test_idmap.cpp
  unittest/utils.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#143 Change binary radius type to float for Jaccard and Tanimoto
  thirdparty/faiss/faiss/IndexBinary.cpp
  thirdparty/faiss/faiss/IndexBinary.h
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryFlat.h
  thirdparty/faiss/faiss/IndexBinaryHash.cpp
  thirdparty/faiss/faiss/IndexBinaryHash.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVF.h
  thirdparty/faiss/faiss/MetaIndexes.cpp
  thirdparty/faiss/faiss/MetaIndexes.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#144 Refactor range search for binary idmap
  knowhere/CMakeLists.txt
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/VecIndex.h
  knowhere/index/vector_index/helpers/DynamicResultSet.cpp
  knowhere/index/vector_index/helpers/DynamicResultSet.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryFlat.h
  thirdparty/faiss/faiss/utils/BinaryDistance.cpp
  thirdparty/faiss/faiss/utils/BinaryDistance.h
  thirdparty/faiss/faiss/utils/hamming.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
  unittest/utils.h
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#145 Optimize IVF unittest
  knowhere/common/Exception.h
  knowhere/index/vector_index/VecIndexFactory.cpp
  unittest/CMakeLists.txt
  unittest/Helper.h
  unittest/test_ivf.cpp
  unittest/test_ivf_gpu_nm.cpp
  unittest/test_ivf_hnsw.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#146 Move VecIndex.h/VecIndexFactory.cpp/VecIndexFactory.h to directory index
  knowhere/CMakeLists.txt
  knowhere/index/VecIndex.h
  knowhere/index/VecIndexFactory.cpp
  knowhere/index/VecIndexFactory.h
  knowhere/index/vector_index/IndexAnnoy.h
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexBinaryIVF.h
  knowhere/index/vector_index/IndexHNSW.h
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/IndexIVF.h
  knowhere/index/vector_index/IndexRHNSW.h
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#147 Create bitset in DataGen for unittest
  knowhere/utils/BitsetView.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_common.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
  unittest/test_ngtonng.cpp
  unittest/test_ngtpanng.cpp
  unittest/test_nsg.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#149 Support range search for IVF
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVF.h
  thirdparty/faiss/faiss/utils/distances.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#150 Support range search for binary ivf
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexBinaryIVF.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVF.h
  thirdparty/faiss/faiss/utils/jaccard-inl.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_ivf.cpp
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#152 Upgrade to annoy-1.17.0
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexAnnoy.h
  thirdparty/annoy/examples/precision_test.cpp
  thirdparty/annoy/examples/s_compile_cpp.sh
  thirdparty/annoy/src/annoygomodule.h
  thirdparty/annoy/src/annoylib.h
  thirdparty/annoy/src/annoyluamodule.cc
  thirdparty/annoy/src/annoymodule.cc
  thirdparty/annoy/src/mman.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed
