Repository milvus-io/knowhere, pull requests merged in 2022-05, with the labels that each got.

#154 Remove unused install deps
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#155 Support range search for IVF_NM
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#156 Optimize benchmark
  build-support/lint_exclusions.txt
  unittest/benchmark/benchmark_faiss_ref.log
  unittest/benchmark/benchmark_faiss_test.cpp
  unittest/benchmark/benchmark_knowhere_ref.log
  unittest/benchmark/benchmark_knowhere_test.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#158 Change index_type to std::string_view instead of const char*
  knowhere/CMakeLists.txt
  knowhere/index/IndexType.cpp
  knowhere/index/IndexType.h
  knowhere/index/VecIndexFactory.cpp
  knowhere/index/vector_index/ConfAdapterMgr.cpp
  knowhere/index/vector_index/IndexRHNSW.cpp
  knowhere/index/vector_index/Statistics.h
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#159 Replace Macros with inline APIs
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/ConfAdapter.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#160 Change metric_type to std::string_view instead of const char*
  knowhere/common/Typedef.h
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexAnnoy.h
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVFHNSW.cpp
  knowhere/index/vector_index/IndexIVFPQ.cpp
  knowhere/index/vector_index/IndexIVFSQ.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.h
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  knowhere/index/vector_index/IndexRHNSWSQ.h
  knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVFPQ.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVFSQ.cpp
  knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  knowhere/index/vector_index/helpers/IndexParameter.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
  unittest/Helper.h
  unittest/benchmark/benchmark_knowhere_test.cpp
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
  unittest/test_nsg.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#162 Remove unused interface GetVectorById and QueryById
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVF.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  unittest/test_binaryivf.cpp
  unittest/test_idmap.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#165 Change IndexParams to std::string_view
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVFHNSW.cpp
  knowhere/index/vector_index/IndexIVFPQ.cpp
  knowhere/index/vector_index/IndexIVFSQ.cpp
  knowhere/index/vector_index/IndexRHNSW.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWPQ.cpp
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/Helper.h
  unittest/benchmark/benchmark_knowhere_test.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#166 Optimize coding style in IndexParameter.h
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.h
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  knowhere/index/vector_index/IndexRHNSWSQ.h
  knowhere/index/vector_index/helpers/IndexParameter.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/Helper.h
  unittest/benchmark/benchmark_knowhere_test.cpp
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
  unittest/test_ngtonng.cpp
  unittest/test_ngtpanng.cpp
  unittest/test_nsg.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
  unittest/test_sptag.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#167 Reload interface GetMetricType
  knowhere/index/vector_index/helpers/IndexParameter.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#168 Fix parameter check error
  knowhere/index/vector_index/ConfAdapter.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#169 Distinguish index parameter PQ::M from HNSW::M
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIVFHNSW.cpp
  knowhere/index/vector_index/IndexIVFPQ.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWPQ.cpp
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/Helper.h
  unittest/test_hnsw.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#173 Check param data type
  knowhere/index/vector_index/ConfAdapter.cpp
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#174 Throw exception when param check fail
  knowhere/common/Exception.h
  knowhere/index/vector_index/ConfAdapter.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#175 Remove redundant interface IndexSize() and UpdateIndexSize()
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexAnnoy.h
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexBinaryIVF.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVF.h
  knowhere/index/vector_index/IndexIVFHNSW.cpp
  knowhere/index/vector_index/IndexIVFHNSW.h
  knowhere/index/vector_index/IndexIVFPQ.cpp
  knowhere/index/vector_index/IndexIVFPQ.h
  knowhere/index/vector_index/IndexIVFSQ.cpp
  knowhere/index/vector_index/IndexIVFSQ.h
  knowhere/index/vector_index/IndexNGT.cpp
  knowhere/index/vector_index/IndexNGT.h
  knowhere/index/vector_index/IndexNGTONNG.cpp
  knowhere/index/vector_index/IndexNGTONNG.h
  knowhere/index/vector_index/IndexNGTPANNG.cpp
  knowhere/index/vector_index/IndexNGTPANNG.h
  knowhere/index/vector_index/IndexRHNSW.cpp
  knowhere/index/vector_index/IndexRHNSW.h
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.h
  knowhere/index/vector_index/IndexRHNSWPQ.cpp
  knowhere/index/vector_index/IndexRHNSWPQ.h
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  knowhere/index/vector_index/IndexRHNSWSQ.h
  knowhere/index/vector_index/IndexSPTAG.cpp
  knowhere/index/vector_index/IndexSPTAG.h
  knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  knowhere/index/vector_index/gpu/IndexIVFSQHybrid.h
  knowhere/index/vector_index/helpers/Cloner.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  knowhere/index/vector_offset_index/IndexNSG_NM.cpp
  knowhere/index/vector_offset_index/IndexNSG_NM.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_gpuresource.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_hnsw.cpp
  unittest/test_ivf_nm.cpp
  unittest/test_ngtonng.cpp
  unittest/test_ngtpanng.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
  unittest/test_sptag.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#176 Merge RHNSW unittest into one file
  unittest/CMakeLists.txt
  unittest/Helper.h
  unittest/test_rhnsw.cpp
  unittest/test_rhnsw_flat.cpp
  unittest/test_rhnsw_pq.cpp
  unittest/test_rhnsw_sq8.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#179 Enable faiss build with ccache
  thirdparty/faiss/CMakeLists.txt
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#180 Fix GPU index size calculation
  knowhere/index/vector_index/IndexIVFSQ.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVF.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#181 Throw exception when call GPU range search
  knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVF.h
  knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
  knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.h
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#188 Move range search check APIs to range_utils.h
  unittest/Helper.h
  unittest/range_utils.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#189 Support range search for HNSW
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  knowhere/index/vector_index/adapter/VectorAdapter.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  unittest/Helper.h
  unittest/test_hnsw.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#190 Optimize benchmark code structure
  unittest/benchmark/benchmark_faiss_test.cpp
  unittest/benchmark/benchmark_knowhere_perf.cpp
  unittest/benchmark/benchmark_knowhere_test.cpp
  unittest/benchmark/benchmark_sift.h
  unittest/benchmark/ref_log/benchmark_faiss_ref.log
  unittest/benchmark/ref_log/benchmark_knowhere_ref.log
Labels: lgtm, approved, size/XXL, dco-passed, do-not-merge/missing-related-issue

#191 Knowhere GPU support
  knowhere/CMakeLists.txt
  knowhere/common/BlockingQueue.h
  knowhere/index/VecIndexFactory.cpp
  knowhere/index/vector_index/gpu/GPUIndex.h
  knowhere/index/vector_index/gpu/IndexGPUIDMAP.h
  knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVFPQ.cpp
  knowhere/index/vector_index/gpu/IndexGPUIVFSQ.cpp
  knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  knowhere/index/vector_index/helpers/Cloner.h
  knowhere/index/vector_index/helpers/FaissGpuResourceMgr.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  python/setup.py
  thirdparty/CMakeLists.txt
  thirdparty/faiss/.gitignore
  thirdparty/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/gpu/GpuIndexFlat.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFFlat.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFPQ.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFSQHybrid.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFScalarQuantizer.cu
  thirdparty/faiss/faiss/gpu/test/CMakeLists.txt
  thirdparty/faiss/faiss/invlists/InvertedLists.h
  unittest/CMakeLists.txt
  unittest/test_customized_index.cpp
  unittest/test_gpuresource.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, size/L, dco-passed, do-not-merge/missing-related-issue

#197 fix compile on Mac when HOMEBREW_PREFIX is /opt/homebrew
  CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#199 Support to get vector raw data from faiss index
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexBinaryIVF.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVF.h
  knowhere/index/vector_index/adapter/VectorAdapter.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  thirdparty/faiss/faiss/Index.cpp
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexBinary.cpp
  thirdparty/faiss/faiss/IndexBinary.h
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryFlat.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVF.h
  thirdparty/faiss/faiss/IndexFlat.cpp
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed
