Repository milvus-io/knowhere, pull requests merged in 2022-12, with the labels that each got.

#575 Fix thread safety in hnsw
  thirdparty/hnswlib/hnswlib/visited_list_pool.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#576 Let range search accept distance square as radius
  knowhere/archive/BruteForce.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/benchmark/benchmark_base.h
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_multi.cpp
  unittest/range_utils.h
  unittest/test_bruteforce.cpp
  unittest/test_diskann.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#578 Let range search accept distance square as radius
  benchmark/benchmark_base.h
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/benchmark_knowhere_float.cpp
  src/common/comp/brute_force.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_diskann.cc
  tests/ut/utils.h
Labels: lgtm, size/M

#580 Add more unittests in test_config
  tests/ut/test_config.cc
Labels: lgtm, size/L

#585 Set result dataset ownership
  include/knowhere/dataset.h
Labels: lgtm, size/XS

#588 Add API GenResultDataSet() for get vector by ids
  include/knowhere/dataset.h
  src/index/annoy/annoy.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
Labels: lgtm, size/M

#587 Add index type IVF_FLAT_NM
  src/index/annoy/annoy.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_search.cc
Labels: size/L

#597 [skip e2e]Add the compilation parameters of diskann to ci
  ci/E2E2.groovy
Labels: size/XS

#596 Split knowhere.h file
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/comp/brute_force.h
  include/knowhere/factory.h
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/object.h
  python/knowhere/knowhere.i
  src/common/factory.cc
  src/common/log.cc
  src/index/annoy/annoy.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/flat_gpu/flat_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_gpu/ivf_gpu.cc
  tests/ut/test_diskann.cc
  tests/ut/test_range_util.cc
  tests/ut/test_search.cc
Labels: size/L

#602 Fix hnsw bitset
  knowhere/index/vector_index/IndexHNSW.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#601 Add search_k scope to k ~ MAX_INT64 for ANNOY
  knowhere/index/vector_index/ConfAdapter.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#604 Support code coverage
  CMakeLists.txt
  scripts/run_codecov.sh
Labels: lgtm, size/S

#599 Add Thread Pool for all indexes in Knowhere
  include/knowhere/expected.h
  include/knowhere/index.h
  include/knowhere/index_node_thread_pool_wrapper.h
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: lgtm, size/L

#607 Support show knowhere version
  CMakeLists.txt
  knowhere/archive/KnowhereConfig.cpp
  knowhere/archive/KnowhereConfig.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#608 Support show knowhere version
  CMakeLists.txt
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
Labels: size/S

#609 Enable debug log
  CMakeLists.txt
  knowhere/index/vector_index/IndexDiskANN.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#594 Diskann support neon compare function and add optimization strategies from 1.3.4
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/include/diskann/cosine_similarity.h
  thirdparty/DiskANN/include/diskann/distance.h
  thirdparty/DiskANN/include/diskann/distance_neon.h
  thirdparty/DiskANN/include/diskann/simd_utils.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/CMakeLists.txt
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/distance_neon.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
Labels: lgtm, size/XL

#611 Fix BruteForce::Search memory leak when metric type invalid
  knowhere/archive/BruteForce.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#583 Update hnsw and diskann in knowhere2
  src/index/hnsw/hnsw.cc
  thirdparty/DiskANN/include/diskann/math_utils.h
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  thirdparty/hnswlib/hnswlib/neighbor.h
  thirdparty/hnswlib/hnswlib/visited_list_pool.h
Labels: size/XL

#613 use little endian
  src/io/FaissIO.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#614 python3 support range search results dump
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: size/M
