Repository milvus-io/knowhere, pull requests merged in 2022-08, with the labels that each got.

#305 Avoid gpu e2e run error
  ci/GpuE2E.groovy
Labels: lgtm, approved, dco-passed, size/XS

#338 Fix dataset trans from numpy int array error
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#340 Relax Diskann's dimension check
  knowhere/index/vector_index/IndexDiskANN.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#336 Add python api for diskann
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  unittest/pycase/test_diskann.py
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#343 Add unit test for DiskANN
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/CMakeLists.txt
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/tests/range_search_disk_index.cpp
  thirdparty/DiskANN/tests/search_disk_index.cpp
  unittest/CMakeLists.txt
  unittest/LocalFileManager.h
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#346 [skip e2e]Add deps for diskAnn
  ci/docker/ubuntu/Dockerfile
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/debug.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#345 Add ci for diskann
  ci/diskAnn.groovy
  ci/pod/diskAnn-build.yaml
  ci/pod/diskAnn-e2e.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, size/L

#347 Remove useless file in DiskANN
  thirdparty/DiskANN/include/index.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#348 [skip e2e]Add mergify rules for diskAnn branch
  .github/mergify.yml
Labels: kind/improvement, ci-passed, dco-passed, size/M

#350 Unify knowhere to use new/delete to sync with faiss
  knowhere/common/Dataset.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexNGT.cpp
  knowhere/index/vector_index/IndexRHNSW.cpp
  knowhere/index/vector_index/adapter/SptagAdapter.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexNSG_NM.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#351 Fix dataset memory leak when use python api
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#337 Fix: query vector copy out of bounds when using InnnerProduct
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#352 Catch diskann exceptions
  knowhere/index/vector_index/IndexDiskANN.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#353 Remove exit() from DiskANN code
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#354 Add unit test for cache and warmup
  knowhere/index/vector_index/IndexDiskANN.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#360 Fix dataset memory leak when use python api
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#356 Fix error message in DiskANN
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#355 Add unittest for build_config check function
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#358 Clean DiskANN log and fix wrong info in output
  .github/workflows/ut.yaml
  CMakeLists.txt
  thirdparty/CMakeLists.txt
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/include/cached_io.h
  thirdparty/DiskANN/include/logger.h
  thirdparty/DiskANN/include/pq_table.h
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/CMakeLists.txt
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
  thirdparty/DiskANN/tests/range_search_disk_index.cpp
  thirdparty/DiskANN/tests/search_disk_index.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#362 Fix GetVectorById() memory leak
  knowhere/common/Dataset.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/utils.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#363 Make Datset type clear when use python
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#365 Fix release version errors occur in ci
  .github/workflows/ut.yaml
  CMakeLists.txt
  thirdparty/CMakeLists.txt
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/src/CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#368 Fix diskann python api
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  unittest/pycase/test_diskann.py
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#371 [skip e2e] Add sanitize parameters to debug memory issue
  CMakeLists.txt
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#373 [skip e2e] Add build option to enable sanitizer
  CMakeLists.txt
  build.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#375 Add unit test for bitset
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/tests/range_search_disk_index.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#372 api for concurrency when build and query
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/Helper.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#359 Add unnitest for merged vamana index
  thirdparty/DiskANN/CMakeLists.txt
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#364 Complements to DiskANN log cleaning
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#378 Support lower case metric type for DiskANN python api
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#377 Remove redundant DiskANN files in knwohere
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/tests/CMakeLists.txt
  thirdparty/DiskANN/tests/build_disk_index.cpp
  thirdparty/DiskANN/tests/build_memory_index.cpp
  thirdparty/DiskANN/tests/range_search_disk_index.cpp
  thirdparty/DiskANN/tests/search_disk_index.cpp
  thirdparty/DiskANN/tests/search_memory_index.cpp
  thirdparty/DiskANN/tests/test_incremental_index.cpp
  thirdparty/DiskANN/tests/utils/CMakeLists.txt
  thirdparty/DiskANN/tests/utils/bin_to_fvecs.cpp
  thirdparty/DiskANN/tests/utils/bin_to_tsv.cpp
  thirdparty/DiskANN/tests/utils/calculate_recall.cpp
  thirdparty/DiskANN/tests/utils/compute_groundtruth.cpp
  thirdparty/DiskANN/tests/utils/create_disk_layout.cpp
  thirdparty/DiskANN/tests/utils/float_bin_to_int8.cpp
  thirdparty/DiskANN/tests/utils/fvecs_to_bin.cpp
  thirdparty/DiskANN/tests/utils/fvecs_to_bvecs.cpp
  thirdparty/DiskANN/tests/utils/gen_random_slice.cpp
  thirdparty/DiskANN/tests/utils/generate_pq.cpp
  thirdparty/DiskANN/tests/utils/int8_to_float.cpp
  thirdparty/DiskANN/tests/utils/int8_to_float_scale.cpp
  thirdparty/DiskANN/tests/utils/ivecs_to_bin.cpp
  thirdparty/DiskANN/tests/utils/merge_shards.cpp
  thirdparty/DiskANN/tests/utils/partition_data.cpp
  thirdparty/DiskANN/tests/utils/partition_with_ram_budget.cpp
  thirdparty/DiskANN/tests/utils/rand_data_gen.cpp
  thirdparty/DiskANN/tests/utils/simulate_aggregate_recall.cpp
  thirdparty/DiskANN/tests/utils/tsv_to_bin.cpp
  thirdparty/DiskANN/tests/utils/uint32_to_uint8.cpp
  thirdparty/DiskANN/tests/utils/uint8_to_float.cpp
  thirdparty/DiskANN/tests/utils/vector_analysis.cpp
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#379 Fix DiskANN aio problem
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/include/linux_aligned_file_reader.h
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#370 Update interface BruteForceSearch() and BruteForceRangeSearch()
  knowhere/archive/BruteForce.cpp
  knowhere/archive/BruteForce.h
  unittest/test_bruteforce.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#386 Support propagating c++ exception to python
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#385 Add util function to read file in python api
  python/knowhere/__init__.py
  unittest/pycase/utils/fvecs_to_bin.py
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#381 Fix PQ compress occupies large memory
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#393 Update CI test commands
  ci/GpuE2E.groovy
  ci/Jenkinsfile
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#389 Fix DiskANN omp problem
  thirdparty/DiskANN/src/math_utils.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#394 Fix: the mismatched hash of openblas
  cmake/ThirdPartyPackagesKw.cmake
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#399 [skip e2e] Add parallel test in benchmark
  unittest/benchmark/benchmark_knowhere_float.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#395 Add mutex lock between building and preparation
  knowhere/index/vector_index/IndexDiskANN.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#403 Add thread safe search for faiss IVFFlat
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFThreadSafe.cpp
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#407 Make IndexDiskANN accept shared FileManager
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#380 Fix and optimize DiskANN kmeans code
  thirdparty/DiskANN/src/math_utils.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#408 Update whl name for CI
  ci/GpuE2E.groovy
  ci/Jenkinsfile
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#410 Modify DiskANN build to accept a config struct
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/.github/workflows/pr-test.yml
  thirdparty/DiskANN/.github/workflows/push-test.yml
  thirdparty/DiskANN/include/aux_utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/unit_tester.sh
  thirdparty/DiskANN/workflows/SSD_index.md
  thirdparty/DiskANN/workflows/in_memory_index.md
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#412 Support build acceleration for DiskANN
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/include/aux_utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#406 Make HNSW search thread safe
  knowhere/index/vector_index/IndexHNSW.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#414 [skip e2e] Fix typo in IndexDiskANN
  knowhere/index/vector_index/IndexDiskANN.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#413 Add api to control omp threads for all index
  knowhere/CMakeLists.txt
  knowhere/common/Utils.cpp
  knowhere/common/Utils.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVFPQ.cpp
  knowhere/index/vector_index/IndexIVFSQ.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/Helper.h
  unittest/test_idmap.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#421 [skip e2e]Add deps for new e2e docker image
  ci/docker/ubuntu/scripts/deps/e2e.sh
Labels: kind/improvement, ci-passed, dco-passed, size/XS

#423 [skip e2e]Upgrade hdf for debug image
  ci/docker/ubuntu/scripts/deps/debug.sh
Labels: dco-passed, size/XS

#415 Optimize OpenBLAS compiling
  cmake/ThirdPartyPackagesKw.cmake
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#418 Substitute OpenBLAS for MKL in DiskANN
  cmake/ThirdPartyPackagesKw.cmake
  knowhere/CMakeLists.txt
  scripts/install_deps.sh
  thirdparty/CMakeLists.txt
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/math_utils.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#417 Support Feder for HNSW and IVFFlat
  knowhere/feder/HNSW.h
  knowhere/feder/IVFFlat.h
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  knowhere/index/vector_index/adapter/VectorAdapter.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  unittest/test_hnsw.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#427 [skip e2e]Remove mkl for the base image
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/debug.sh
  ci/docker/ubuntu/scripts/deps/e2e.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#430 Fix diskann python
  python/knowhere/knowhere.i
  python/setup.py
  unittest/pycase/test_diskann.py
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#429 Remove unused pipleine and update new docker image for ci
  ci/diskAnn.groovy
  ci/pod/cpu-build.yaml
  ci/pod/cpu-e2e.yaml
  ci/pod/diskAnn-build.yaml
  ci/pod/diskAnn-e2e.yaml
  ci/pod/gpu-build.yaml
  ci/pod/gpu-e2e.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#433 Add parameter legacy check API CheckRangeSearch()
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/ConfAdapter.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#424 Automate the benchmark env prepration
  build.sh
  unittest/CMakeLists.txt
  unittest/benchmark/README.md
  unittest/benchmark/prepare.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#431 Remove native compile in diskann
  thirdparty/DiskANN/CMakeLists.txt
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#432 Add raw data files and index files check for diskann
  knowhere/index/vector_index/IndexDiskANN.cpp
  unittest/test_diskann.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#440 Fix build error in milvus
  thirdparty/CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#443 [skip e2e] Use UTC instead of Shanghai
  ci/docker/ubuntu/Dockerfile
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#442 Limit the Diskann cached nodes number
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#438 Fix diskann memory problem
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/include/parameters.h
  thirdparty/DiskANN/src/CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/M
