Repository milvus-io/knowhere, pull requests merged in 2022-06, with the labels that each got.

#203 Add benchmark test logs for IVFPQ
  unittest/benchmark/benchmark_faiss.cpp
  unittest/benchmark/benchmark_knowhere_binary.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/ref_log/Makefile
  unittest/benchmark/ref_log/benchmark_faiss.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_hnsw.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_idmap.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_ivf_flat.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_faiss/test_faiss_ivf_sq8.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_tanimoto.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_tanimoto.log
  unittest/benchmark/ref_log/benchmark_knowhere_float.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/ref_log/benchmark_knowhere_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_tanimoto.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/XXL, dco-passed

#204 Add RHNSW benchmark and test logs
  unittest/benchmark/benchmark_knowhere_binary.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/benchmark_knowhere_perf.cpp
  unittest/benchmark/ref_log/Makefile
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_flat.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_sq.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#196 Fix compile error when use gpu
  knowhere/index/VecIndexFactory.cpp
  knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#206 Add benchmark_knowhere_binary_range
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/benchmark_sift.h
  unittest/benchmark/ref_log/Makefile
  unittest/benchmark/ref_log/benchmark_knowhere_binary_range/test_knowhere_binary_range_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary_range/test_knowhere_binary_range_ivf_flat.log
  unittest/range_utils.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#210 Update benchmark logs
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_idmap_tanimoto.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_hamming.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_jaccard.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_tanimoto.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary_range/test_knowhere_binary_range_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_binary_range/test_knowhere_binary_range_ivf_flat.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_flat.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_rhnsw_sq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_idmap.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_ivf_pq.log
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#208 Fix python wrapper swig compile error
  .github/workflows/ut.yaml
  python/knowhere/knowhere.i
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, dco-passed, size/M

#211 Fix workflows error
  .github/workflows/ut.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#212 Free binary set ASAP in benchmark test
  .github/workflows/ut.yaml
  unittest/benchmark/benchmark_knowhere_binary.cpp
  unittest/benchmark/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/benchmark_knowhere_float_range.cpp
  unittest/benchmark/benchmark_knowhere_perf.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#214 Fix hnsw range search error
  knowhere/index/vector_index/IndexHNSW.cpp
  unittest/benchmark/benchmark_knowhere_binary.cpp
  unittest/benchmark/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/benchmark_knowhere_float_range.cpp
  unittest/benchmark/benchmark_knowhere_perf.cpp
  unittest/benchmark/ref_log/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#215 Enable index FAISS_IVFHNSW and update benchmark log
  knowhere/index/VecIndexFactory.cpp
  unittest/benchmark/benchmark_knowhere_float.cpp
  unittest/benchmark/ref_log/Makefile
  unittest/benchmark/ref_log/benchmark_knowhere_float/test_knowhere_ivf_hnsw.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#216 Update IVFHNSW unittest
  unittest/test_ivf_hnsw.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#217 Update some logs to INFO level
  knowhere/archive/KnowhereConfig.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#218 Remove redundant lib dependancy for benchmark
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/README.md
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#220 Update README and OWNERS
  OWNERS
  README.md
Labels: kind/improvement, lgtm, approved, dco-passed, size/S

#223 Update benchmark README
  unittest/benchmark/README.md
Labels: kind/improvement, lgtm, approved, dco-passed, size/S

#225 Move INDEX_FILE_SLICE_SIZE_IN_MEGA to meta::SLICE_SIZE
  knowhere/CMakeLists.txt
  knowhere/archive/KnowhereConfig.cpp
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_index/helpers/Slice.cpp
  knowhere/index/vector_index/helpers/Slice.h
  unittest/Helper.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
  unittest/test_ngtonng.cpp
  unittest/test_ngtpanng.cpp
  unittest/test_nsg.cpp
  unittest/test_sptag.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#227 Change std::string_view back to const char*
  knowhere/common/Dataset.h
  knowhere/index/IndexType.h
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/Statistics.h
  knowhere/index/vector_index/helpers/IndexParameter.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#228 Remove common/MetricType.h
  knowhere/CMakeLists.txt
  knowhere/common/MetricType.h
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVFHNSW.cpp
  knowhere/index/vector_index/IndexIVFPQ.cpp
  knowhere/index/vector_index/IndexIVFSQ.cpp
  knowhere/index/vector_index/IndexRHNSWFlat.cpp
  knowhere/index/vector_index/IndexRHNSWSQ.cpp
  knowhere/index/vector_index/helpers/IndexParameter.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#226 Support setting external vector data pointer for IDMAP/BinaryIDMAP
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  thirdparty/faiss/faiss/Index.cpp
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexBinary.cpp
  thirdparty/faiss/faiss/IndexBinary.h
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryFlat.h
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexFlatCodes.cpp
  thirdparty/faiss/faiss/IndexFlatCodes.h
  unittest/test_binaryidmap.cpp
  unittest/test_idmap.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed
