Repository milvus-io/knowhere, pull requests merged in 2022-10, with the labels that each got.

#492 Add ut for AsyncIndex
  unittest/CMakeLists.txt
  unittest/ThreadChecker.cpp
  unittest/ThreadChecker.h
  unittest/test_async.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#495 [skip e2e] Add deps for code checker into build image
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  ci/docker/ubuntu/scripts/deps/build.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#497 [skip e2e]Add python2 for cpp lint
  ci/docker/ubuntu/scripts/deps/build.sh
Labels: kind/improvement, size/XS

#498 [skip e2e]Add python2 for cpp lint
  ci/docker/ubuntu/scripts/deps/build.sh
Labels: kind/improvement

#488 [skip e2e]Update ut to 20.04
  .github/mergify.yml
  .github/workflows/ut.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#496 Support metric IP for diskann range search
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#499 Re-organize knowhere benchmark
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/README.md
  unittest/benchmark/benchmark_base.h
  unittest/benchmark/hdf5/benchmark_faiss_float.cpp
  unittest/benchmark/hdf5/benchmark_hdf5.h
  unittest/benchmark/hdf5/benchmark_knowhere.h
  unittest/benchmark/hdf5/benchmark_knowhere_binary.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_perf.cpp
  unittest/benchmark/hdf5/ref_log/Makefile
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/gpu/test_knowhere_idmap.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/gpu/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/gpu/test_knowhere_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/gpu/test_knowhere_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_idmap.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/glove/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_faiss/test_faiss_hnsw.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_faiss/test_faiss_idmap.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_faiss/test_faiss_ivf_flat.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_faiss/test_faiss_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_faiss/test_faiss_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_idmap_hamming.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_idmap_jaccard.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_idmap_tanimoto.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_hamming.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_jaccard.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary/test_knowhere_binary_ivf_flat_tanimoto.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary_range/test_knowhere_binary_range_idmap.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_binary_range/test_knowhere_binary_range_ivf_flat.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/gpu/test_knowhere_idmap.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/gpu/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/gpu/test_knowhere_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/gpu/test_knowhere_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/test_knowhere_annoy.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/test_knowhere_hnsw.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/test_knowhere_idmap.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float/test_knowhere_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_idmap.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_pq.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#501 Add benchmark ssnpp
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/benchmark_base.h
  unittest/benchmark/hdf5/benchmark_hdf5.h
  unittest/benchmark/ssnpp/benchmark_knowhere.h
  unittest/benchmark/ssnpp/benchmark_ssnpp.h
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range.cpp
Labels: kind/improvement, approved, size/L, dco-passed

#502 Remove assemble and disassemble util func
  knowhere/CMakeLists.txt
  knowhere/archive/KnowhereConfig.cpp
  knowhere/archive/KnowhereConfig.h
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_index/helpers/Slice.cpp
  knowhere/index/vector_index/helpers/Slice.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#503 Update benchmark SSNPP
  unittest/benchmark/benchmark_base.h
  unittest/benchmark/ssnpp/benchmark_ssnpp.h
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range.cpp
  unittest/benchmark/ssnpp/ref_log/Makefile
  unittest/benchmark/ssnpp/ref_log/test_ssnpp_range_hnsw.log
  unittest/benchmark/ssnpp/ref_log/test_ssnpp_range_ivf_flat_nm.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#505 [skip e2e] Update sift rane search benchmark logs
  unittest/benchmark/hdf5/ref_log/Makefile
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_ivf_sq8.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#506 Remove setting thread omp logs
  knowhere/CMakeLists.txt
  knowhere/common/Utils.cpp
  knowhere/common/Utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#507 Update HNSW range search benchmark
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range/test_knowhere_range_hnsw.log
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#508 Add benchmark qps for search and range search
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/hdf5/benchmark_knowhere_float_qps.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_qps.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_perf.cpp
  unittest/benchmark/hdf5/ref_log/Makefile
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_qps/test_knowhere_qps_hnsw.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_qps/test_knowhere_qps_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_qps/test_knowhere_qps_ivf_sq8.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range_qps/test_knowhere_range_qps_hnsw.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range_qps/test_knowhere_range_qps_ivf_flat_nm.log
  unittest/benchmark/hdf5/ref_log/sift/benchmark_knowhere_float_range_qps/test_knowhere_range_qps_ivf_sq8.log
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#509 Remove HNSW range search parameter range_k, use ef instead
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_qps.cpp
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range.cpp
  unittest/test_hnsw.cpp
Labels: kind/improvement, lgtm, approved, dco-passed, size/M

#510 Update SSNPP benchmark
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/benchmark_base.h
  unittest/benchmark/ssnpp/benchmark_ssnpp.h
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range.cpp
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range_qps.cpp
  unittest/benchmark/ssnpp/ref_log/Makefile
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#511 Update SSNPP benchmark test name
  unittest/benchmark/CMakeLists.txt
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range_multi.cpp
  unittest/benchmark/ssnpp/benchmark_ssnpp_float_range_multi_qps.cpp
  unittest/benchmark/ssnpp/ref_log/Makefile
  unittest/benchmark/ssnpp/ref_log/benchmark_ssnpp_float_range_multi/test_ssnpp_range_multi_hnsw.log
  unittest/benchmark/ssnpp/ref_log/benchmark_ssnpp_float_range_multi/test_ssnpp_range_multi_ivf_flat_nm.log
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#515 [skip e2e] Update benchmark readme
  unittest/benchmark/README.md
  unittest/benchmark/prepare.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#516 Pass CMAKE_PREFIX_PATH to externla project
  thirdparty/CMakeLists.txt
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#513 Add ctpl as ThreadPool and use it in HNSW search
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  thirdparty/CMakeLists.txt
  thirdparty/ctpl/ctpl-std.h
  thirdparty/ctpl/ctpl.h
Labels: lgtm, approved, ci-passed, size/XL, dco-passed
