Repository milvus-io/knowhere, pull requests merged in 2022-02, with the labels that each got.

#62 Temporarily remove OMP as issue #15585 hotfix (Mac Only).
  CMakeLists.txt
  knowhere/index/vector_index/impl/bruteforce/BruteForce.cpp
Labels: lgtm, approved, size/S

#65 Update OpenBLAS to 0.3.19
  cmake/ThirdPartyPackagesKw.cmake
  thirdparty/OpenBLAS/CMakeLists.txt
  thirdparty/versions.txt
Labels: approved, size/L

#67 Pre-install libopenblas-dev for ubuntu18.04
  .github/workflows/ut.yaml
  scripts/install_deps.sh
Labels: approved, size/XS

#66 Temporarily remove OMP as issue #15585 hotfix (Mac Only).
  CMakeLists.txt
  knowhere/knowhere/index/vector_index/impl/bruteforce/BruteForce.cpp
Labels: approved, size/S

#70 Rename Macro USE_CPU to USE_GPU
  thirdparty/CMakeLists.txt
  thirdparty/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.h
Labels: lgtm, approved, size/L

#71 Rename Makefile to Makefile.tmp
  thirdparty/faiss/Makefile.tmp
Labels: approved, size/XS

#72 Pre-install libopenblas-dev only for ut
  .github/workflows/ut.yaml
  scripts/install_deps.sh
Labels: approved, size/S

#73 Enable faiss_test in UT
  .github/workflows/ut.yaml
Labels: lgtm, approved, size/XS

#74 Add centos7 support
  .github/workflows/release.yaml
  .github/workflows/ut.yaml
  scripts/install_deps.sh
Labels: lgtm, approved, dco-passed, size/M

#76 Fix build issue in centos
  .github/workflows/release.yaml
  .github/workflows/ut.yaml
  CMakeLists.txt
  knowhere/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: lgtm, approved, size/S

#75 Change openblas back to 0.3.10 for centos
  cmake/ThirdPartyPackagesKw.cmake
  thirdparty/versions.txt
Labels: lgtm, approved, size/XS
