Repository milvus-io/knowhere, pull requests merged in 2022-09, with the labels that each got.

#444 Modify DiskANN config file
  build-support/cpplint.py
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#445 Set the uppperbound of search_list in DiskANN
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#446 Change diskann build config parameter (search_dram_budget_gb) to (pq_code_budget_gb)
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/include/aux_utils.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/pycase/test_diskann.py
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#447 Modify clang-tidy according our style
  .clang-tidy
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#448 Change diskann parameters (cached number nodes) to (search cache budget)
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/pycase/test_diskann.py
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#452 Add default values to diskann parameters
  knowhere/index/vector_index/IndexDiskANNConfig.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#458 Fix IVF_SQ8 and IVF_PQ range search return deleted ids
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFPQ.cpp
  unittest/range_utils.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_bruteforce.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#453 Add more compute capability support
  thirdparty/CMakeLists.txt
  thirdparty/faiss/CMakeLists.txt
Labels: dco-passed, size/XS

#461 Support Feder for HNSW range search
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  unittest/test_hnsw.cpp
Labels: lgtm, approved, size/L, dco-passed, do-not-merge/missing-related-issue

#464 [skip e2e] Update openblas for images
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/debug.sh
  ci/docker/ubuntu/scripts/deps/e2e.sh
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#465 [skip e2e] Fix e2e image
  ci/docker/ubuntu/scripts/deps/e2e.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed

#467 [skip e2e] Remove debug image
  .github/workflows/publish-docker.yaml
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/e2e.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#460 Make Num/Count available right after build
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#469 optimize openblas compile in pod
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/e2e.sh
  knowhere/CMakeLists.txt
  scripts/install_deps.sh
Labels: lgtm, approved, ci-passed, dco-passed, size/S, do-not-merge/missing-related-issue

#450 Move build and e2e into one pod
  .github/mergify.yml
  ci/E2E.groovy
  ci/GpuE2E.groovy
  ci/Jenkinsfile
  ci/pod/cpu-build.yaml
  ci/pod/cpu-e2e.yaml
  ci/pod/e2e.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed, do-not-merge/hold

#462 Fix knowhere always compile openblas
  ci/pod/e2e.yaml
  cmake/ThirdPartyPackagesKw.cmake
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/math_utils.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#471 Get dim from HNSW index
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexHNSW.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#472 Optimize lapack library
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/e2e.sh
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#470 Remove unnecessary denpendancies for DiskANN
  ci/docker/ubuntu/scripts/deps/build.sh
  ci/docker/ubuntu/scripts/deps/debug.sh
  scripts/install_deps.sh
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#474 Update ci env
  ci/pod/cpu-build.yaml
  ci/pod/cpu-e2e.yaml
  ci/pod/e2e.yaml
  ci/pod/gpu-build.yaml
  ci/pod/gpu-e2e.yaml
Labels: kind/improvement, lgtm, approved, size/L, dco-passed

#475 Update ci env
  ci/pod/e2e.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#476 Support infinite dim for DiskANN
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/gtest/CMakeLists.txt
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#479 Correct range search radius scope
  knowhere/index/vector_index/ConfAdapter.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#480 Use brute force search to get all element link lists
  knowhere/index/vector_index/IndexHNSW.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#483 [skip e2e] Add Build.groovy
  ci/Build.groovy
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#484 Add some building logs for diskann
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  thirdparty/DiskANN/src/aux_utils.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#487 Fix bugs use async index
  unittest/AsyncIndex.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#489 Fix large degree error in DiskANN
  thirdparty/DiskANN/src/aux_utils.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#491 Print error message when the function abnormal returns
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S
