Repository milvus-io/knowhere, pull requests merged in 2022-01, with the labels that each got.

#36 Add owner file and delete status files
  OWNERS
  knowhere/CMakeLists.txt
  knowhere/knowhere/archive/KnowhereConfig.h
  knowhere/knowhere/common/Error.h
  knowhere/knowhere/common/Status.cpp
  knowhere/knowhere/common/Status.h
Labels: lgtm, approved, size/L

#37 Fix ut fail does not exit issue
  .github/workflows/ut.yaml
  build/run_ut.sh
Labels: kind/improvement, lgtm, size/M

#39 Update .gitignore
  .gitignore
Labels: approved, size/S

#40 Add release build action
  .github/workflows/release.yaml
Labels: kind/improvement, size/M

#41 Fix action error
  .github/workflows/release.yaml
Labels: kind/improvement, size/XS

#44 Remove target knowhere_log
  knowhere/CMakeLists.txt
  unittest/CMakeLists.txt
Labels: lgtm, approved, size/S

#45 Disable NGT static lib install
  thirdparty/NGT/lib/NGT/CMakeLists.txt
Labels: lgtm, approved, size/XS

#47 Enable shared library for knowhere target.
  CMakeLists.txt
  knowhere/CMakeLists.txt
Labels: lgtm, approved, size/XS

#43 Add documentation for knowhere project.
  README.md
Labels: lgtm, approved, size/M

#48 As required, replace "APPLE" with "MATCHES Darwin" and use "MACOS" in sub cmakes.
  CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: lgtm, approved, size/S

#49 Fix build error
  knowhere/knowhere/index/Index.h
Labels: approved, size/XS

#50 Update knowhere default version to 1.0.0
  CMakeLists.txt
Labels: approved, size/XS

#51 Fix build error
  knowhere/knowhere/index/Index.h
Labels: approved, size/XS

#52 Update build.sh
  build.sh
Labels: approved, size/S

#54 Move cache into knowhere
  knowhere/knowhere/cache/DataObj.h
  knowhere/knowhere/index/Index.h
Labels: lgtm, approved, size/XS

#55 Remove useless files
  knowhere/Makefile
  knowhere/cmake_install.cmake
Labels: lgtm, approved, size/XXL

#56 Remove cache install
  knowhere/CMakeLists.txt
Labels: lgtm, approved, size/XS

#57 Enable ccache to speed up build
  .github/workflows/ut.yaml
  cmake/BuildUtilsKw.cmake
Labels: lgtm, approved, size/XS

#59 Rename directory build to scripts
  .github/workflows/release.yaml
  .github/workflows/ut.yaml
  README.md
  build.sh
  scripts/install_deps.sh
Labels: approved, size/M

#60 Support check code coverage
  .gitignore
  scripts/run_codecov.sh
  unittest/CMakeLists.txt
Labels: lgtm, approved, size/L
