Repository milvus-io/knowhere, pull requests merged in 2023-03, with the labels that each got.

#710 Remove unused index types IVF_SQ8H/RHNSW from thirdparty/faiss
  thirdparty/faiss/faiss/IndexRHNSW.cpp
  thirdparty/faiss/faiss/IndexRHNSW.h
  thirdparty/faiss/faiss/IndexSQHybrid.cpp
  thirdparty/faiss/faiss/IndexSQHybrid.h
  thirdparty/faiss/faiss/clone_index.cpp
  thirdparty/faiss/faiss/clone_index.h
  thirdparty/faiss/faiss/gpu/GpuCloner.cpp
  thirdparty/faiss/faiss/gpu/GpuCloner.h
  thirdparty/faiss/faiss/gpu/GpuIndexIVFSQHybrid.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFSQHybrid.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/index_factory.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XXL, dco-passed

#711 Make GPU index search thread safe
  src/index/ivf_gpu/ivf_gpu.cc
  thirdparty/faiss/faiss/gpu/GpuIndex.h
  thirdparty/faiss/faiss/gpu/GpuIndexFlat.h
  thirdparty/faiss/faiss/gpu/GpuIndexIVFFlat.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFFlat.h
  thirdparty/faiss/faiss/gpu/GpuIndexIVFPQ.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFPQ.h
  thirdparty/faiss/faiss/gpu/GpuIndexIVFScalarQuantizer.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFScalarQuantizer.h
  thirdparty/faiss/faiss/gpu/GpuIndexThreadSafe.cu
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#713 remove redundant optimize flags
  cmake/utils/compile_flags.cmake
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#714 Let config accept both int and float as float type
  include/knowhere/config.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#716 Use shared_ptr for index_ in index node
  src/index/flat/flat.cc
  src/index/flat_gpu/flat_gpu.cc
  src/index/ivf/ivf.cc
  src/index/ivf_gpu/ivf_gpu.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#717 Set cudaStream for gpu resource
  CMakeLists.txt
  include/knowhere/gpu/gpu_res_mgr.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#720 Update mergify
  .github/mergify.yml
Labels: kind/improvement, dco-passed, size/M

#718 Fix TANIMOTO BruteForce distance calculation wrong
  knowhere/archive/BruteForce.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#719 Fix TANIMOTO BruteForce distance calculation wrong
  src/common/comp/brute_force.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#721 Add GPU device validation check when init
  include/knowhere/gpu/gpu_res_mgr.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#724 Make BinaryIVF thread safe
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexBinaryIVFThreadSafe.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#725 Set config check log to debug level
  include/knowhere/index.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#712 Provide support for RAFT-based indexes
  CMakeLists.txt
  cmake/libs/fetch_rapids.cmake
  cmake/libs/libcutlass.cmake
  cmake/libs/libraft.cmake
  cmake/libs/librmm.cmake
  include/knowhere/expected.h
  include/knowhere/gpu/gpu_res_mgr.h
  src/common/raft_metric.h
  src/index/ivf_raft/ivf_flat_raft.cu
  src/index/ivf_raft/ivf_pq_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
  src/index/ivf_raft/ivf_raft_config.h
  tests/ut/test_search.cc
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#732 Fix crash when sort nan/inf
  thirdparty/DiskANN/CMakeLists.txt
Labels: lgtm, approved, size/XS

#735 Fix a benchmark error to find smallest search param
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#736 Update GPU knowhere version
  src/common/comp/knowhere_config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#737 Update QPS benchmark
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#740 Update QPS benchmark
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#738 Free the memory of medoids
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#734 adapt for raft ivf
  benchmark/CMakeLists.txt
  benchmark/prepare.sh
  include/knowhere/comp/index_param.h
  include/knowhere/gpu/gpu_res_mgr.h
  src/index/ivf_raft/ivf_pq_raft.cu
  src/index/ivf_raft/ivf_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
Labels: lgtm, approved, size/L, dco-passed

#743 disable debug log when build release version
  cmake/libs/libeasylogging.cmake
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#746 Add for building gpu-builder image
  ci/pod/builder-build.yaml
Labels: size/S

#751 Add Sanity Check after HNSW Build
  CMakeLists.txt
  knowhere/CMakeLists.txt
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/helpers/Slice.cpp
  thirdparty/CMakeLists.txt
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/segvcatch/CMakeLists.txt
  thirdparty/segvcatch/i386-signal.h
  thirdparty/segvcatch/segvcatch.cpp
  thirdparty/segvcatch/segvcatch.h
  thirdparty/segvcatch/x86_64-signal.h
  unittest/test_hnsw.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#752 Support GPU init in python test
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
  ci/BuildGPUBuilderImage.groovy
  ci/docker/set_docker_mirror.sh
  include/knowhere/gpu/gpu_res_mgr.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#747 Add more log for diskann
  CMakeLists.txt
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#741 Fix pq hang out when distance overflow
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  unittest/test_diskann.cpp
  unittest/test_hnsw.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#728 Use conan to manage depedency
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  CMakeLists.txt
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  cmake/libs/libdiskann.cmake
  conanfile.py
  python/setup.py
  scripts/install_deps.sh
  tests/ut/CMakeLists.txt
  thirdparty/gtest/CMakeLists.txt
  thirdparty/nlohmann/json.hpp
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#760 Add more logs to HNSW index
  knowhere/index/vector_index/IndexHNSW.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#768 Add legal json keys
  include/knowhere/comp/index_param.h
  src/common/config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#764 Add Sanity Check, Query after Build
  knowhere/CMakeLists.txt
  knowhere/index/VecIndex.h
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexAnnoy.h
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  unittest/test_annoy.cpp
  unittest/test_async.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#763 improve gpu compile options
  CMakeLists.txt
  README.md
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#771 Rename GPU index type names
  include/knowhere/comp/index_param.h
  src/index/flat_gpu/flat_gpu.cc
  src/index/ivf_gpu/ivf_gpu.cc
  src/index/ivf_raft/ivf_raft.cu
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#776 Fix RAFT index type name
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_gpu_search.cc
  tests/ut/test_search.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#753 Optimze conan better
  .gitignore
  CMakeLists.txt
  README.md
  benchmark/CMakeLists.txt
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
  ci/E2E2.groovy
  conanfile.py
  tests/ut/test_search.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#783 Fix TANIMOTO BruteForce distance calculation wrong
  src/common/comp/brute_force.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#780 fix ut ci error
  CMakeLists.txt
  ci/UT_GPU.groovy
  cmake/libs/libfaiss.cmake
  cmake/utils/compile_flags.cmake
  conanfile.py
  src/common/comp/knowhere_config.cc
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_gpu_search.cc
  tests/ut/utils.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#756 Support prometheus metrics
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  CMakeLists.txt
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  cmake/libs/libprometheus.cmake
  include/knowhere/comp/prometheus_client.h
  scripts/install_deps.sh
  src/common/prometheus_client.cc
  tests/ut/test_prometheus.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#785 Support deserialize from file and mmap for faiss
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#781 Fix io_setup EAGAIN errorno
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#784 Fix threadpool init
  include/knowhere/comp/thread_pool.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#787 [skip e2e] Update mergify for gpu e2e
  .github/mergify.yml
Labels: kind/improvement, ci-passed, dco-passed, size/XS

#786 Show -gpu in knowhere version
  src/common/comp/knowhere_config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#790 [skip e2e] Add upload action when Release
  .github/workflows/release.yaml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M
