Repository milvus-io/knowhere, pull requests merged in 2023-04, with the labels that each got.

#793 update raft
  CMakeLists.txt
  benchmark/hdf5/benchmark_knowhere_float.cpp
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
  ci/UT_GPU.groovy
  cmake/libs/libraft.cmake
  cmake/utils/compile_flags.cmake
  cmake/utils/fetch_rapids.cmake
  conanfile.py
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/flat_gpu/flat_gpu_config.h
  src/index/gpu/gpu_res_mgr.h
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu_config.h
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#791 Support GetVectorByIds for ANNOY, HNSW and all faiss index types
  src/index/annoy/annoy.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_get_vector.cc
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#798 Fix DiskANN Access Invalid Address when Query with Bitset
  thirdparty/DiskANN/include/diskann/neighbor.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#799 Add prometheus-cpp to conan
  CMakeLists.txt
  cmake/libs/libprometheus.cmake
  conanfile.py
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#802 Support GetVectorByIds for DiskANN
  src/index/diskann/diskann.cc
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
  tests/ut/utils.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#805 Support GetVectorByIds for DiskANN IP Metric
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#807 Rename Timer to time_recorder
  include/knowhere/comp/time_recorder.h
  src/common/comp/time_recorder.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#806 Fix DiskANN Access Invalid Address when Query with Bitset (#798)
  thirdparty/DiskANN/include/neighbor.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#809 Change the Ef limit for HNSW when topk is large
  knowhere/index/vector_index/ConfAdapter.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#813 Remove HNSW param ef invalid check from ut
  tests/ut/test_config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#815 Optimize GetVectorByIds, get dim from index and save rows/dim into result dataset
  include/knowhere/dataset.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_get_vector.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#816 Clean ut build warnings
  tests/ut/test_get_vector.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#817 Remove prometheus-cpp::pull dependency
  CMakeLists.txt
  conanfile.py
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#811 Change the Ef limit for HNSW when topk is large
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#820 Update python API to support GetVectorByIds
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#777 Add some log for hnsw index
  src/index/hnsw/hnsw.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#822 raft index, fix param m and add env for setting gpu mem pool size
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
  src/index/ivf_raft/ivf_raft.cuh
  src/index/ivf_raft/ivf_raft_config.h
  src/index/ivf_raft/set_pool.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#827 Merge GetVectorByIds for BinIVF and IVF
  src/index/ivf/ivf.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#825 Add API GenIdsDataSet()
  include/knowhere/dataset.h
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#812 Add metric type COSINE
  include/knowhere/comp/brute_force.h
  include/knowhere/comp/index_param.h
  include/knowhere/utils.h
  src/common/comp/brute_force.cc
  src/common/metric.h
  src/common/utils.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_utils.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#828 Add API HasRawData() for get vector
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/index_node_thread_pool_wrapper.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#794 Use Brute Force when Bitset Filter Rate is High
  include/knowhere/heap.h
  tests/ut/test_diskann.cc
  tests/ut/test_heap.cc
  tests/ut/test_search.cc
  tests/ut/test_utils.cc
  tests/ut/utils.h
  thirdparty/DiskANN/include/diskann/defines_export.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#819 Build Python Wheels on manylinux x86 and Upload to PyPI
  .github/workflows/release-python.yml
  .github/workflows/ut.yaml
  .gitignore
  CMakeLists.txt
  include/knowhere/log.h
  python/knowhere/numpy.i
  python/setup.py
  scripts/python_deps.sh
  src/io/fileIO.h
  src/simd/distances_sse.cc
  tests/python/test_index_with_random.py
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#829 Update HNSW Brute Force Threshold While Searching with Bitset
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#824 add ivf_flat_cc index
  include/knowhere/comp/index_param.h
  include/knowhere/comp/thread_pool.h
  include/knowhere/config.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/python/test_index_random.py
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
  tests/ut/test_get_vector.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/invlists/DirectMap.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.h
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#830 Update legal json keys
  src/common/config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#833 fix some warnings
  include/knowhere/config.h
  src/common/config.cc
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/invlists/InvertedLists.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#835 Add benchmake for diskann
  benchmark/hdf5/benchmark_knowhere_float.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#837 Update HasRawData() for all index types
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#840 Expose HasRawData() for python
  python/knowhere/knowhere.i
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#841 Update benchmark qps
  benchmark/hdf5/benchmark_knowhere_float_qps.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#842 Use SIMD to optimize normalize
  include/knowhere/utils.h
  src/common/utils.cc
  src/index/ivf/ivf.cc
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/hook.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#843 [Cherry-Pick]Add cache for query
  knowhere/common/Utils.h
  knowhere/common/lru_cache.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#834 Add cache for query
  include/knowhere/utils.h
  src/common/lru_cache.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#845 Optimize diskann unittest
  tests/ut/test_diskann.cc
  tests/ut/test_search.cc
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, size/L, dco-passed

#847 Add round_decimal and offset as valid key
  src/common/config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS
