Repository milvus-io/knowhere, pull requests merged in 2023-02, with the labels that each got.

#647 Add range search ut
  tests/ut/test_search.cc
Labels: lgtm, size/M

#648 Remove the distance calculation of diskann's deleted node
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#651 Delete useless config in tests params
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
  tests/ut/test_diskann.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#650 add invalid json key check
  include/knowhere/config.h
  include/knowhere/expected.h
  include/knowhere/index.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#652 Release useless mem in diskann index
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#653 opt and fix
  include/knowhere/config.h
  src/common/config.cc
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#656 fix bug
  include/knowhere/config.h
Labels: size/XS

#654 Fix ut memory leak
  tests/ut/test_range_util.cc
Labels: kind/improvement, lgtm, size/S

#659 opt code and asan for ut
  .github/workflows/ut.yaml
  include/knowhere/config.h
  src/common/config.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#658 Fix diskann filter
  thirdparty/DiskANN/include/neighbor.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#661 [Cherry-Pick]Fix diskann filter (#658)
  thirdparty/DiskANN/include/diskann/neighbor.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, size/S

#662 Update omp thread num to 1
  knowhere/archive/BruteForce.cpp
  thirdparty/ctpl/ctpl-std.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#660 Use defaultRangeFilter to decide range_filter exist or not
  include/knowhere/config.h
  src/common/comp/brute_force.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_search.cc
Labels: lgtm, size/S

#665 opt cmake include directories and support cmake fetchcontext
  CMakeLists.txt
  src/io/FaissIO.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#666 avoid gcc type infer error
  include/knowhere/binaryset.h
  include/knowhere/config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#667 Remove useless memory malloc in diskann
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#668 Remove useless memory alloc in diskann
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#669 Limit hnsw params range
  src/index/hnsw/hnsw_config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#670 Add some config case
  src/common/config.cc
  tests/ut/test_config.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#671 adapt for milvus
  CMakeLists.txt
  cmake/libs/libfaiss.cmake
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#672 avoid param overflow
  include/knowhere/config.h
  include/knowhere/expected.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#673 Limit parameters value
  src/index/annoy/annoy_config.h
  src/index/diskann/diskann_config.h
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf_config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#675 avoid gcc type infer bug
  include/knowhere/config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#676 adapt workflow and ci for branch main
  .github/mergify.yml
  .github/workflows/analyzer.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/ut.yaml
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#679 adapt for gcc11 std library
  include/knowhere/dataset.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#682 adapt for gcc11 std library
  include/knowhere/binaryset.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#689 Fix aio_pool limit exceed
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#688 mac os m1 for loop version
  cmake/libs/libfaiss.cmake
  src/common/range_util.cc
  src/simd/hook.cc
  thirdparty/annoy/src/annoylib.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVFThreadSafe.cpp
  thirdparty/faiss/faiss/IndexReplicas.cpp
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/impl/io.cpp
  thirdparty/faiss/faiss/utils/simdlib_neon.h
  thirdparty/faiss/faiss/utils/utils.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#681 [skip e2e]Update mergify
  .github/mergify.yml
Labels: kind/improvement, ci-passed, dco-passed, size/M

#690 [skip e2e] Add release workflow for main branch
  .github/workflows/release.yaml
Labels: kind/improvement, dco-passed, size/M

#693 Fix GPU index build error
  src/index/flat/flat.cc
  src/index/flat_gpu/flat_gpu.cc
  src/index/flat_gpu/flat_gpu_config.h
  src/index/ivf_gpu/ivf_gpu.cc
  src/index/ivf_gpu/ivf_gpu_config.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#694 Enable ccache
  CMakeLists.txt
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#695 Use -O0 for debug build
  cmake/utils/compile_flags.cmake
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#697 [Cherry-Pick]Fix aio read
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#691 [skip e2e]Update release-build workflow
  .github/workflows/release.yaml
Labels: kind/improvement, lgtm, approved, dco-passed, size/XS

#698 Add groovy file for e2e-gpu
  ci/E2E_GPU.groovy
Labels: kind/improvement, dco-passed, size/M

#699 Add groovy file for ut-gpu
  .github/mergify.yml
  ci/UT_GPU.groovy
Labels: kind/improvement, dco-passed, size/M

#702 Split queries in IVF and BF
  knowhere/archive/BruteForce.cpp
  knowhere/common/ThreadPool.h
  knowhere/index/VecIndexFactory.cpp
  knowhere/index/vector_index/FaissBaseIndex.h
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/OffsetBaseIndex.h
  thirdparty/ctpl/ctpl-std.h
Labels: kind/improvement, lgtm, approved, size/L, dco-passed, do-not-merge/missing-related-issue

#703 [Cherry-Pick]Split queries in IVF and BF
  include/knowhere/comp/thread_pool.h
  src/common/comp/brute_force.cc
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#704 Need return load status
  src/common/comp/brute_force.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#701 Add level config key
  src/common/config.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#708 Caiyd support gpu bench
  CMakeLists.txt
  benchmark/CMakeLists.txt
  benchmark/hdf5/benchmark_knowhere_float.cpp
  include/knowhere/comp/blocking_queue.h
  include/knowhere/comp/index_param.h
  include/knowhere/comp/knowhere_config.h
  include/knowhere/gpu/gpu_res_mgr.h
  src/common/comp/knowhere_config.cc
  src/index/flat_gpu/flat_gpu.cc
  src/index/flat_gpu/flat_gpu_config.h
  src/index/ivf_gpu/ivf_gpu.cc
  src/index/ivf_gpu/ivf_gpu_config.h
  tests/ut/CMakeLists.txt
  tests/ut/test_gpu_search.cc
  tests/ut/test_search.cc
Labels: lgtm, approved, ci-passed, size/XL, dco-passed
