Repository milvus-io/knowhere, pull requests merged in 2023-01, with the labels that each got.

#618 Fix range search result error
  benchmark/hdf5/benchmark_knowhere.h
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf_config.h
Labels: size/S

#621 Clang tidy
  .clang-tidy
  .clang-tidy-ignore
  .github/mergify.yml
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  include/knowhere/bitsetview.h
  include/knowhere/config.h
  include/knowhere/dataset.h
  include/knowhere/expected.h
  src/common/comp/knowhere_config.cc
  src/index/annoy/annoy.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.h
  src/simd/distances_ref.cc
  src/simd/instruction_set.h
  thirdparty/annoy/src/annoylib.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#623 fix memory leak when use python api
  python/knowhere/knowhere.i
  python/setup.py
Labels: lgtm, size/M

#626 add logo
  README.md
  static/knowhere-logo.png
Labels: approved, ci-passed, dco-passed, size/XS

#627 enable clang-tidy analyzer for diskann
  .github/workflows/analyzer.yaml
  src/index/diskann/diskann.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#622 Replace cblas_sgemm_ functions by lapack sgemm_ and remove support uint8/int8 in diskann
  README.md
  include/knowhere/comp/local_file_manager.h
  python/knowhere/knowhere.i
  src/index/diskann/diskann.cc
  tests/python/test_diskann.py
  tests/ut/test_diskann.cc
  tests/ut/utils.h
  thirdparty/DiskANN/include/diskann/math_utils.h
  thirdparty/DiskANN/src/math_utils.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#595 Add some parameters check and ut
  include/knowhere/config.h
  include/knowhere/expected.h
  src/index/annoy/annoy_config.h
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf.cc
  tests/ut/test_diskann.cc
  tests/ut/test_search.cc
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#630 rewrite diskann cmake and format all cmake file
  CMakeLists.txt
  cmake/libs/libdiskann.cmake
  cmake/libs/libfaiss.cmake
  cmake/modules/Findaio.cmake
  cmake/utils/compile_flags.cmake
  cmake/utils/utils.cmake
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/ann_exception.cpp
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/distance_neon.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
  thirdparty/DiskANN/src/logger.cpp
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/memory_mapper.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec.h
  thirdparty/hnswlib/hnswlib/neighbor.h
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#610 Add aio pool
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
  thirdparty/DiskANN/include/diskann/aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/linux_aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#631 Fix range search benchmark wrong with IP metric type
  benchmark/benchmark_base.h
  benchmark/hdf5/benchmark_knowhere_float_range.cpp
Labels: size/S

#632 Fix range search benchmark wrong with IP metric type
  unittest/benchmark/benchmark_base.h
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#633 warning as error
  .clang-tidy
  src/index/diskann/diskann.cc
Labels: size/XS

#634 Replace diskann distance function by faiss distance function
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  thirdparty/DiskANN/CMakeLists.txt
  thirdparty/DiskANN/include/cosine_similarity.h
  thirdparty/DiskANN/include/distance.h
  thirdparty/DiskANN/include/index.h
  thirdparty/DiskANN/include/percentile_stats.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
  unittest/AsyncIndex.h
Labels: lgtm, approved, ci-passed, size/XXL, dco-passed

#637 Enable diskann when ut and swig build
  .github/workflows/ut.yaml
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#616 Add knowhere::status, bitset, binaryset in python api
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  tests/python/test_diskann.py
  tests/python/test_index_load_and_save.py
  tests/python/test_index_random.py
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#635 Use param radius and range_filter for range search
  knowhere/archive/BruteForce.cpp
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  knowhere/index/vector_index/helpers/RangeUtil.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_binary_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_multi.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_multi_qps.cpp
  unittest/benchmark/hdf5/benchmark_knowhere_float_range_qps.cpp
  unittest/range_utils.h
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_bruteforce.cpp
  unittest/test_diskann.cpp
  unittest/test_hnsw.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf.cpp
  unittest/test_ivf_nm.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#642 [skip e2e] Fix apt-get update failed
  ci/E2E2.groovy
Labels: size/XS

#640 Reduce memory usage of ivf-flat index
  src/index/ivf/ivf.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#641 add ELPP_THREAD_SAFE in code, index format check results
  CMakeLists.txt
  cmake/libs/libeasylogging.cmake
  include/knowhere/config.h
  include/knowhere/index.h
  include/knowhere/log.h
  python/setup.py
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#643 fix memory leak and centos install error
  CMakeLists.txt
  src/index/ivf/ivf.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#644 Limit the range of parameters
  src/index/annoy/annoy_config.h
  src/index/ivf/ivf_config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#646 Return error status if give float type data to int parameter
  include/knowhere/config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS
