Repository milvus-io/knowhere, pull requests merged in 2023-06, with the labels that each got.

#913 Add some prometheus metrics
  include/knowhere/expected.h
  include/knowhere/index.h
  include/knowhere/prometheus_client.h
  src/common/comp/time_recorder.cc
  src/common/prometheus_client.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#914 reduce cuda stream concurency
  src/index/ivf_raft/ivf_raft.cu
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#902 Add some logs
  include/knowhere/config.h
  python/setup.py
  src/common/comp/brute_force.cc
  src/common/config.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#907 Remove useless KnowhereConfig APIs
  include/knowhere/comp/knowhere_config.h
  include/knowhere/config.h
  include/knowhere/log.h
  src/common/comp/knowhere_config.cc
  tests/ut/test_knowhere_init.cc
  thirdparty/faiss/faiss/utils/utils.cpp
  thirdparty/faiss/faiss/utils/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#869 Add cosine for diskann
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#917 bitset check count
  src/index/ivf_raft/ivf_raft.cuh
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#878 Build cache list in diskann build process
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
  thirdparty/DiskANN/include/diskann/aux_utils.h
  thirdparty/DiskANN/include/diskann/index.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/pq_table.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#923 Set search_list(ef) default size and throw exception if search list(ef) < topk
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#924 Sync perform of HNSW/DiskANN
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/test_diskann.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#925 Prepare DiskANN during deserialization（test e2e）
  include/knowhere/config.h
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/index_node_thread_pool_wrapper.h
  python/knowhere/knowhere.i
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
  tests/python/test_diskann.py
  tests/ut/test_diskann.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#873 Replace LoadConfig with Config
  include/knowhere/config.h
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/index_node_thread_pool_wrapper.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#926 Use a empty json string as json default value in python api
  python/knowhere/knowhere.i
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#929 Let HNSW search error out if ef smaller than topk
  src/index/hnsw/hnsw.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#932 Let HNSW call bruteforce range search when delete rate is high
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#933 Refactor GPU filtering logic for greater robustness
  include/knowhere/device_bitset.h
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_gpu_search.cc
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#935 Improve DiskANN GetVectorByIds Performance
  src/index/diskann/diskann.cc
  tests/ut/test_diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#903 Disable query cache while tuning
  include/knowhere/config.h
  src/common/config.cc
  src/index/diskann/diskann.cc
  src/index/hnsw/hnsw.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#937 Fix wrong file name in GetOptionalFilenames() function
  src/index/diskann/diskann.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#940 [skip e2e]Update groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#938 Rename benchmark test names
  benchmark/CMakeLists.txt
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/ref_logs/Makefile
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#942 optimize gpu code and add cagra impl
  CMakeLists.txt
  include/knowhere/comp/index_param.h
  src/common/raft/raft.cu
  src/common/raft/res_pool.cu
  src/common/raft/res_pool.cuh
  src/index/cagra/cagra.cu
  src/index/cagra/cagra_config.h
  src/index/ivf_raft/ivf_raft.cuh
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#936 Sync HNSW ef behavior with knowhere-1.x
  include/knowhere/config.h
  include/knowhere/index.h
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#915 Refactored expected class to remove unexpected and simplify usage
  include/knowhere/comp/brute_force.h
  include/knowhere/expected.h
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/index_node_thread_pool_wrapper.h
  src/common/comp/brute_force.cc
  src/common/metric.h
  src/common/raft_metric.h
  src/index/cagra/cagra.cu
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_ivfflat_cc.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/XL, dco-passed

#945 Let HNSW range search accept default ef
  include/knowhere/config.h
  include/knowhere/index.h
  src/index/hnsw/hnsw_config.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#948 Fix diskann cosine distance calculation
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#951 Merge Train/Add to Build
  include/knowhere/index_node.h
  include/knowhere/index_node_thread_pool_wrapper.h
  src/index/cagra/cagra.cu
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#949 Add test_feder
  scripts/run_codecov.sh
  src/common/range_util.cc
  src/common/range_util.h
  tests/ut/test_feder.cc
  tests/ut/test_search.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#955 Add more unittest to improve coverage
  src/simd/hook.cc
  tests/ut/test_heap.cc
  tests/ut/test_knowhere_init.cc
  tests/ut/test_search.cc
  tests/ut/test_utils.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#957 Fix GetVectorById Dim, Return Dataset and Set All HasRawData to False Except HNSW
  knowhere/index/vector_index/IndexAnnoy.cpp
  knowhere/index/vector_index/IndexAnnoy.h
  knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  knowhere/index/vector_index/IndexBinaryIDMAP.h
  knowhere/index/vector_index/IndexBinaryIVF.cpp
  knowhere/index/vector_index/IndexBinaryIVF.h
  knowhere/index/vector_index/IndexHNSW.cpp
  knowhere/index/vector_index/IndexIDMAP.cpp
  knowhere/index/vector_index/IndexIDMAP.h
  knowhere/index/vector_index/IndexIVF.cpp
  knowhere/index/vector_index/IndexIVF.h
  knowhere/index/vector_index/adapter/VectorAdapter.cpp
  knowhere/index/vector_index/adapter/VectorAdapter.h
  knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  knowhere/index/vector_offset_index/IndexIVF_NM.h
  unittest/test_annoy.cpp
  unittest/test_binaryidmap.cpp
  unittest/test_binaryivf.cpp
  unittest/test_idmap.cpp
  unittest/test_ivf_nm.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#958 Add test_bruteforce to improve code coverage
  tests/ut/test_bruteforce.cc
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#963 use optional for config define
  include/knowhere/config.h
  src/common/comp/brute_force.cc
  src/common/config.cc
  src/index/cagra/cagra.cu
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_config.cc
  tests/ut/test_diskann.cc
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#959 Add test_simd to improve code coverage
  src/simd/hook.cc
  tests/ut/test_bruteforce.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_knowhere_init.cc
  tests/ut/test_simd.cc
  tests/ut/utils.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#966 Sync param check for DiskANN and HNSW
  include/knowhere/config.h
  include/knowhere/index.h
  src/index/diskann/diskann_config.h
  src/index/hnsw/hnsw_config.h
  tests/ut/test_config.cc
  tests/ut/test_diskann.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#972 Add binary unittest to improve code coverage
  tests/ut/test_get_vector.cc
  tests/ut/test_knowhere_init.cc
  tests/ut/test_search.cc
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#976 shorter diskann ut run time
  src/index/diskann/diskann.cc
  tests/ut/test_diskann.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#970 expected support error message
  include/knowhere/config.h
  include/knowhere/expected.h
  src/common/config.cc
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#965 Temporary remove cagra code
  CMakeLists.txt
  src/index/ivf_raft/ivf_raft_config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/XS
