Repository milvus-io/knowhere, pull requests merged in 2023-07, with the labels that each got.

#978 HNSW support binary vector
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  src/index/hnsw/hnsw.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_search.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  thirdparty/hnswlib/hnswlib/space_hamming.h
  thirdparty/hnswlib/hnswlib/space_jaccard.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#977 Minor cleanup of json key validation
  src/common/config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#954 Update OWNERS
  OWNERS
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#962 Pipeline GetVectorByIds and Not Use ThreadPool
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
  thirdparty/DiskANN/include/diskann/aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/linux_aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#967 Remove extra virtual in signature
  src/index/cagra/cagra.cu
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#980 fix ivfflatcc cosine
  include/knowhere/utils.h
  src/common/utils.cc
  src/index/ivf/ivf.cc
  tests/ut/test_ivfflat_cc.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/IndexIVFPQ.cpp
  thirdparty/faiss/faiss/IndexIVFPQ.h
  thirdparty/faiss/faiss/IndexIVFPQR.cpp
  thirdparty/faiss/faiss/IndexIVFPQR.h
  thirdparty/faiss/faiss/IndexIVFSpectralHash.cpp
  thirdparty/faiss/faiss/IndexIVFThreadSafe.cpp
  thirdparty/faiss/faiss/IndexScalarQuantizer.cpp
  thirdparty/faiss/faiss/IndexScalarQuantizer.h
  thirdparty/faiss/faiss/impl/ScalarQuantizer.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/invlists/BlockInvertedLists.cpp
  thirdparty/faiss/faiss/invlists/BlockInvertedLists.h
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.h
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.cpp
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.h
  thirdparty/faiss/tests/test_dealloc_invlists.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#982 add distances test case
  tests/ut/test_distances.cc
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#981 In Index::Search pass the config load error message to the returned status
  include/knowhere/index.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#953 Refactor device resource management to control memory usage
  src/common/comp/knowhere_config.cc
  src/common/raft/raft_utils.h
  src/common/raft/res_pool.cu
  src/common/raft/res_pool.cuh
  src/index/cagra/cagra.cu
  src/index/ivf_raft/ivf_raft.cuh
  src/index/ivf_raft/ivf_raft_config.h
  src/index/ivf_raft/set_pool.h
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#983 Refactor binary metrics implementation
  benchmark/hdf5/ref_logs/Makefile
  src/common/comp/brute_force.cc
  src/index/ivf/ivf.cc
  tests/ut/test_search.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexBinaryFlat.cpp
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVFThreadSafe.cpp
  thirdparty/faiss/faiss/IndexLSH.cpp
  thirdparty/faiss/faiss/IndexPQ.cpp
  thirdparty/faiss/faiss/utils/binary_distances.cpp
  thirdparty/faiss/faiss/utils/binary_distances.h
  thirdparty/faiss/faiss/utils/hamming-inl.h
  thirdparty/faiss/faiss/utils/jaccard-inl.h
  thirdparty/faiss/faiss/utils/structure-inl.h
  thirdparty/faiss/faiss/utils/substructure-inl.h
  thirdparty/faiss/faiss/utils/superstructure-inl.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/space_hamming.h
  thirdparty/hnswlib/hnswlib/space_jaccard.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/XXL, dco-passed

#984 Update diskann benchmark
  CMakeLists.txt
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/ref_logs/Makefile
  src/common/comp/knowhere_config.cc
  tests/ut/test_search.cc
  tests/ut/test_simd.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#986 update readme for macOS
  README.md
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#991 Fix init aio pool
  cmake/libs/libdiskann.cmake
  src/common/comp/knowhere_config.cc
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#987 modify neon macro name
  thirdparty/DiskANN/include/diskann/distance_neon.h
  thirdparty/DiskANN/include/diskann/pq_table.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#990 Update prometheus metrics
  include/knowhere/index.h
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#993 Update install_deps.sh
  CMakeLists.txt
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#788 Use folly threadpool
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  CMakeLists.txt
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  conanfile.py
  include/knowhere/comp/ctpl/ctpl-std.h
  include/knowhere/comp/ctpl/ctpl.h
  include/knowhere/comp/thread_pool.h
  include/knowhere/index_node_thread_pool_wrapper.h
  python/setup.py
  src/common/comp/brute_force.cc
  src/common/index_node_thread_pool_wrapper.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#985 Update cache
  include/knowhere/utils.h
  src/common/lru_cache.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#996 Change DeserializeFromFile config parameter to JSON
  include/knowhere/index.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#997 Fix: memory overflow for test code
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#1000 Fix HNSW range search result wrong
  src/common/range_util.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#1001 Fix benchmark compile
  conanfile.py
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#1002 Update GetVectorByIds unittest
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, dco-passed, size/S

#1003 Fix diskann range search error for COSINE
  tests/ut/test_diskann.cc
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#1008 Sync diskann range search behavior with other index type
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#1006 Fix unmap for HNSW
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#1011 Sync diskann COSINE distance calculation with IP
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#1009 Set dist func while load index from file for HNSW
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#1012 Optimize bitset check in faiss
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFPQ.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#1015 Refine mmap implement for HNSW
  include/knowhere/utils.h
  src/io/fileIO.h
  tests/ut/test_mmap.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, size/XL, dco-passed
