Repository milvus-io/knowhere, pull requests merged in 2023-05, with the labels that each got.

#850 raft index support bitset filter
  src/index/ivf_raft/ivf_raft.cuh
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#856 Fix bug that pollute the first vector in PQ generation
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#853 Avoid Excessive Bit Tests when All Data is Filtered in HNSW
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#831 Use PQ and Refine for DiskANN when Bitset Filter Ratio is High
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
  tests/ut/test_search.cc
  tests/ut/utils.h
  thirdparty/DiskANN/include/diskann/defines_export.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#854 Fix data conversion method in generate_pq_data_from_pivots() function
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: lgtm, approved, dco-passed, size/XS

#810 Add mdspan API to raft IVF functions
  CMakeLists.txt
  README.md
  cmake/libs/libraft.cmake
  cmake/utils/fetch_rapids.cmake
  src/index/ivf_raft/ivf_raft.cuh
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#849 HNSW COSINE support GetVectorByIds
  src/index/hnsw/hnsw.cc
  tests/ut/test_search.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  thirdparty/hnswlib/hnswlib/space_cosine.h
  thirdparty/hnswlib/hnswlib/space_ip.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#860 Show DEBUG in knowhere version for debug build
  src/common/comp/knowhere_config.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#863 Update json dump debug logs
  include/knowhere/index.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#861 [Cherry-Pick] Use BF for HNSW and PQ+Refine for DiskANN when Filter Ratio is High
  knowhere/common/Heap.h
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/include/utils.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
  unittest/CMakeLists.txt
  unittest/test_common.cpp
  unittest/test_diskann.cpp
  unittest/test_hnsw.cpp
  unittest/test_utils.cpp
  unittest/utils.cpp
  unittest/utils.h
Labels: lgtm, approved, ci-passed, size/XL, dco-passed

#865 Update get vector ut
  tests/ut/test_get_vector.cc
  tests/ut/utils.h
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#867 Roll back #842 to fix IVF_PQ and BIN_IVF_FLAT recall degrade
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/hook.cc
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#868 Update GetVectorByIds interface
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/index_node_thread_pool_wrapper.h
  python/knowhere/knowhere.i
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#875 optimize gpu bitset filter
  CMakeLists.txt
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: lgtm, approved, ci-passed, size/L, dco-passed

#874 Update index BinarySet key name to be compatible with knowhere-1.x
  include/knowhere/binaryset.h
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#848 Release python GIL when calling C++
  python/knowhere/knowhere.i
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#885 Fix HNSW COSINE recall fallback
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#887 Let Deserialize() return empty_binary_set when key invalid
  include/knowhere/expected.h
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#886 fix raft compile error in milvus and optize bitset filter
  CMakeLists.txt
  cmake/libs/libraft.cmake
  cmake/utils/fetch_rapids.cmake
  src/index/ivf_raft/ivf_raft.cuh
  src/index/ivf_raft/ivf_raft_config.h
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#889 Sync behavior of GetByName() and GetByNames() for BinarySet
  include/knowhere/binaryset.h
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#890 Support coverage in conan
  conanfile.py
  scripts/run_codecov.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#894 update nvidia rapids version
  cmake/utils/fetch_rapids.cmake
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#897 Set DiskAnn Filter Threshold to Default Value when Missing
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#893 Enable github codecov
  .github/workflows/ut.yaml
  codecov.yml
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#899 Move prometheus_client.h to common
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
  tests/ut/test_prometheus.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#904 [Cherry-Pick] Fix diskann ip low recall for unnormalized data
  thirdparty/DiskANN/include/index.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#905 Fix python wheel build
  python/setup.py
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#906 Update release.yaml and install_deps.sh
  .github/workflows/release.yaml
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, ci-passed, size/L, dco-passed

#909 Set default search_list_size by k
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/M

#908 Set Build & Search default param
  knowhere/index/vector_index/ConfAdapter.cpp
  knowhere/index/vector_index/helpers/IndexParameter.h
  unittest/Helper.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#911 Modify the search list size if this value not set in struct or too small
  knowhere/index/vector_index/IndexDiskANNConfig.cpp
  knowhere/index/vector_index/IndexDiskANNConfig.h
  unittest/test_diskann.cpp
Labels: lgtm, approved, ci-passed, dco-passed, size/S

#912 Update IVF & HNSW default params
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf_config.h
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S
