Repository milvus-io/knowhere, pull requests merged in 2023-08, with the labels that each got.

#1007 [skip e2e]Add conan remote address
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#1004 fix folly compile problem
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  CMakeLists.txt
  cmake/libs/libdiskann.cmake
  conanfile.py
  scripts/install_deps.sh
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#1020 Set error message for HNSW search params check
  include/knowhere/config.h
  include/knowhere/index.h
  src/index/diskann/diskann_config.h
  src/index/hnsw/hnsw_config.h
  tests/ut/test_config.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/M

#1026 fix fmt cmake find error
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  CMakeLists.txt
Labels: lgtm, approved, ci-passed, dco-passed, size/XS

#1016 Adopt new strategy for faiss IVF range search
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVFThreadSafe.cpp
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFPQ.cpp
  thirdparty/faiss/faiss/IndexIVFSpectralHash.cpp
  thirdparty/faiss/faiss/IndexIVFThreadSafe.cpp
Labels: kind/improvement, lgtm, approved, size/L, dco-passed

#1024 Remove info log of normalizing query while searching with cosine metric
  src/common/utils.cc
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/XS

#1027 Remove parallel_mode
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFThreadSafe.cpp
Labels: kind/improvement, lgtm, approved, ci-passed, dco-passed, size/S

#1031 update readme
  README.md
Labels: approved, size/XS
